/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.api;

public class charArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected charArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(charArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete_charArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public charArray(int nelements) {
    this(tiledbJNI.new_charArray(nelements), true);
  }

  public char getitem(int index) {
    return tiledbJNI.charArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, char value) {
    tiledbJNI.charArray_setitem(swigCPtr, this, index, value);
  }

  public String cast() {
    return tiledbJNI.charArray_cast(swigCPtr, this);
  }

  public static charArray frompointer(String t) {
    long cPtr = tiledbJNI.charArray_frompointer(t);
    return (cPtr == 0) ? null : new charArray(cPtr, false);
  }

}
