/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.api;

public class tiledbUtils {
  public static SWIGTYPE_p_int new_intp() {
    long cPtr = tiledbUtilsJNI.new_intp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    long cPtr = tiledbUtilsJNI.copy_intp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    tiledbUtilsJNI.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    tiledbUtilsJNI.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    return tiledbUtilsJNI.intp_value(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static SWIGTYPE_p_float new_floatp() {
    long cPtr = tiledbUtilsJNI.new_floatp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static SWIGTYPE_p_float copy_floatp(float value) {
    long cPtr = tiledbUtilsJNI.copy_floatp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static void delete_floatp(SWIGTYPE_p_float obj) {
    tiledbUtilsJNI.delete_floatp(SWIGTYPE_p_float.getCPtr(obj));
  }

  public static void floatp_assign(SWIGTYPE_p_float obj, float value) {
    tiledbUtilsJNI.floatp_assign(SWIGTYPE_p_float.getCPtr(obj), value);
  }

  public static float floatp_value(SWIGTYPE_p_float obj) {
    return tiledbUtilsJNI.floatp_value(SWIGTYPE_p_float.getCPtr(obj));
  }

  public static SWIGTYPE_p_p_int new_intpp() {
    long cPtr = tiledbUtilsJNI.new_intpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_p_int copy_intpp(SWIGTYPE_p_int value) {
    long cPtr = tiledbUtilsJNI.copy_intpp(SWIGTYPE_p_int.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_int(cPtr, false);
  }

  public static void delete_intpp(SWIGTYPE_p_p_int obj) {
    tiledbUtilsJNI.delete_intpp(SWIGTYPE_p_p_int.getCPtr(obj));
  }

  public static void intpp_assign(SWIGTYPE_p_p_int obj, SWIGTYPE_p_int value) {
    tiledbUtilsJNI.intpp_assign(SWIGTYPE_p_p_int.getCPtr(obj), SWIGTYPE_p_int.getCPtr(value));
  }

  public static SWIGTYPE_p_int intpp_value(SWIGTYPE_p_p_int obj) {
    long cPtr = tiledbUtilsJNI.intpp_value(SWIGTYPE_p_p_int.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_p_char new_charpp() {
    long cPtr = tiledbUtilsJNI.new_charpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static SWIGTYPE_p_p_char copy_charpp(String value) {
    long cPtr = tiledbUtilsJNI.copy_charpp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static void delete_charpp(SWIGTYPE_p_p_char obj) {
    tiledbUtilsJNI.delete_charpp(SWIGTYPE_p_p_char.getCPtr(obj));
  }

  public static void charpp_assign(SWIGTYPE_p_p_char obj, String value) {
    tiledbUtilsJNI.charpp_assign(SWIGTYPE_p_p_char.getCPtr(obj), value);
  }

  public static String charpp_value(SWIGTYPE_p_p_char obj) {
    return tiledbUtilsJNI.charpp_value(SWIGTYPE_p_p_char.getCPtr(obj));
  }

  public static SWIGTYPE_p_unsigned_int new_uintp() {
    long cPtr = tiledbUtilsJNI.new_uintp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_int copy_uintp(long value) {
    long cPtr = tiledbUtilsJNI.copy_uintp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public static void delete_uintp(SWIGTYPE_p_unsigned_int obj) {
    tiledbUtilsJNI.delete_uintp(SWIGTYPE_p_unsigned_int.getCPtr(obj));
  }

  public static void uintp_assign(SWIGTYPE_p_unsigned_int obj, long value) {
    tiledbUtilsJNI.uintp_assign(SWIGTYPE_p_unsigned_int.getCPtr(obj), value);
  }

  public static long uintp_value(SWIGTYPE_p_unsigned_int obj) {
    return tiledbUtilsJNI.uintp_value(SWIGTYPE_p_unsigned_int.getCPtr(obj));
  }

  public static SWIGTYPE_p_unsigned_long_long new_ullp() {
    long cPtr = tiledbUtilsJNI.new_ullp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_long_long copy_ullp(java.math.BigInteger value) {
    long cPtr = tiledbUtilsJNI.copy_ullp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public static void delete_ullp(SWIGTYPE_p_unsigned_long_long obj) {
    tiledbUtilsJNI.delete_ullp(SWIGTYPE_p_unsigned_long_long.getCPtr(obj));
  }

  public static void ullp_assign(SWIGTYPE_p_unsigned_long_long obj, java.math.BigInteger value) {
    tiledbUtilsJNI.ullp_assign(SWIGTYPE_p_unsigned_long_long.getCPtr(obj), value);
  }

  public static java.math.BigInteger ullp_value(SWIGTYPE_p_unsigned_long_long obj) {
    return tiledbUtilsJNI.ullp_value(SWIGTYPE_p_unsigned_long_long.getCPtr(obj));
  }

  public static SWIGTYPE_p_tiledb_config_t new_tiledb_config_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_config_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_config_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_config_t copy_tiledb_config_tp(SWIGTYPE_p_tiledb_config_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_config_tp(SWIGTYPE_p_tiledb_config_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_config_t(cPtr, false);
  }

  public static void delete_tiledb_config_tp(SWIGTYPE_p_tiledb_config_t obj) {
    tiledbUtilsJNI.delete_tiledb_config_tp(SWIGTYPE_p_tiledb_config_t.getCPtr(obj));
  }

  public static void tiledb_config_tp_assign(SWIGTYPE_p_tiledb_config_t obj, SWIGTYPE_p_tiledb_config_t value) {
    tiledbUtilsJNI.tiledb_config_tp_assign(SWIGTYPE_p_tiledb_config_t.getCPtr(obj), SWIGTYPE_p_tiledb_config_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_config_t tiledb_config_tp_value(SWIGTYPE_p_tiledb_config_t obj) {
    return new SWIGTYPE_p_tiledb_config_t(tiledbUtilsJNI.tiledb_config_tp_value(SWIGTYPE_p_tiledb_config_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_config_t new_tiledb_config_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_config_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_config_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_config_t copy_tiledb_config_tpp(SWIGTYPE_p_tiledb_config_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_config_tpp(SWIGTYPE_p_tiledb_config_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_config_t(cPtr, false);
  }

  public static void delete_tiledb_config_tpp(SWIGTYPE_p_p_tiledb_config_t obj) {
    tiledbUtilsJNI.delete_tiledb_config_tpp(SWIGTYPE_p_p_tiledb_config_t.getCPtr(obj));
  }

  public static void tiledb_config_tpp_assign(SWIGTYPE_p_p_tiledb_config_t obj, SWIGTYPE_p_tiledb_config_t value) {
    tiledbUtilsJNI.tiledb_config_tpp_assign(SWIGTYPE_p_p_tiledb_config_t.getCPtr(obj), SWIGTYPE_p_tiledb_config_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_config_t tiledb_config_tpp_value(SWIGTYPE_p_p_tiledb_config_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_config_tpp_value(SWIGTYPE_p_p_tiledb_config_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_config_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_config_iter_t new_tiledb_config_iter_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_config_iter_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_config_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_config_iter_t copy_tiledb_config_iter_tp(SWIGTYPE_p_tiledb_config_iter_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_config_iter_tp(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_config_iter_t(cPtr, false);
  }

  public static void delete_tiledb_config_iter_tp(SWIGTYPE_p_tiledb_config_iter_t obj) {
    tiledbUtilsJNI.delete_tiledb_config_iter_tp(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(obj));
  }

  public static void tiledb_config_iter_tp_assign(SWIGTYPE_p_tiledb_config_iter_t obj, SWIGTYPE_p_tiledb_config_iter_t value) {
    tiledbUtilsJNI.tiledb_config_iter_tp_assign(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(obj), SWIGTYPE_p_tiledb_config_iter_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_config_iter_t tiledb_config_iter_tp_value(SWIGTYPE_p_tiledb_config_iter_t obj) {
    return new SWIGTYPE_p_tiledb_config_iter_t(tiledbUtilsJNI.tiledb_config_iter_tp_value(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_config_iter_t new_tiledb_config_iter_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_config_iter_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_config_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_config_iter_t copy_tiledb_config_iter_tpp(SWIGTYPE_p_tiledb_config_iter_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_config_iter_tpp(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_config_iter_t(cPtr, false);
  }

  public static void delete_tiledb_config_iter_tpp(SWIGTYPE_p_p_tiledb_config_iter_t obj) {
    tiledbUtilsJNI.delete_tiledb_config_iter_tpp(SWIGTYPE_p_p_tiledb_config_iter_t.getCPtr(obj));
  }

  public static void tiledb_config_iter_tpp_assign(SWIGTYPE_p_p_tiledb_config_iter_t obj, SWIGTYPE_p_tiledb_config_iter_t value) {
    tiledbUtilsJNI.tiledb_config_iter_tpp_assign(SWIGTYPE_p_p_tiledb_config_iter_t.getCPtr(obj), SWIGTYPE_p_tiledb_config_iter_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_config_iter_t tiledb_config_iter_tpp_value(SWIGTYPE_p_p_tiledb_config_iter_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_config_iter_tpp_value(SWIGTYPE_p_p_tiledb_config_iter_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_config_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_ctx_t new_tiledb_ctx_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_ctx_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_ctx_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_ctx_t copy_tiledb_ctx_tp(SWIGTYPE_p_tiledb_ctx_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_ctx_tp(SWIGTYPE_p_tiledb_ctx_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_ctx_t(cPtr, false);
  }

  public static void delete_tiledb_ctx_tp(SWIGTYPE_p_tiledb_ctx_t obj) {
    tiledbUtilsJNI.delete_tiledb_ctx_tp(SWIGTYPE_p_tiledb_ctx_t.getCPtr(obj));
  }

  public static void tiledb_ctx_tp_assign(SWIGTYPE_p_tiledb_ctx_t obj, SWIGTYPE_p_tiledb_ctx_t value) {
    tiledbUtilsJNI.tiledb_ctx_tp_assign(SWIGTYPE_p_tiledb_ctx_t.getCPtr(obj), SWIGTYPE_p_tiledb_ctx_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_ctx_t tiledb_ctx_tp_value(SWIGTYPE_p_tiledb_ctx_t obj) {
    return new SWIGTYPE_p_tiledb_ctx_t(tiledbUtilsJNI.tiledb_ctx_tp_value(SWIGTYPE_p_tiledb_ctx_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_ctx_t new_tiledb_ctx_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_ctx_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_ctx_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_ctx_t copy_tiledb_ctx_tpp(SWIGTYPE_p_tiledb_ctx_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_ctx_tpp(SWIGTYPE_p_tiledb_ctx_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_ctx_t(cPtr, false);
  }

  public static void delete_tiledb_ctx_tpp(SWIGTYPE_p_p_tiledb_ctx_t obj) {
    tiledbUtilsJNI.delete_tiledb_ctx_tpp(SWIGTYPE_p_p_tiledb_ctx_t.getCPtr(obj));
  }

  public static void tiledb_ctx_tpp_assign(SWIGTYPE_p_p_tiledb_ctx_t obj, SWIGTYPE_p_tiledb_ctx_t value) {
    tiledbUtilsJNI.tiledb_ctx_tpp_assign(SWIGTYPE_p_p_tiledb_ctx_t.getCPtr(obj), SWIGTYPE_p_tiledb_ctx_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_ctx_t tiledb_ctx_tpp_value(SWIGTYPE_p_p_tiledb_ctx_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_ctx_tpp_value(SWIGTYPE_p_p_tiledb_ctx_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_ctx_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_error_t new_tiledb_error_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_error_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_error_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_error_t copy_tiledb_error_tp(SWIGTYPE_p_tiledb_error_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_error_tp(SWIGTYPE_p_tiledb_error_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_error_t(cPtr, false);
  }

  public static void delete_tiledb_error_tp(SWIGTYPE_p_tiledb_error_t obj) {
    tiledbUtilsJNI.delete_tiledb_error_tp(SWIGTYPE_p_tiledb_error_t.getCPtr(obj));
  }

  public static void tiledb_error_tp_assign(SWIGTYPE_p_tiledb_error_t obj, SWIGTYPE_p_tiledb_error_t value) {
    tiledbUtilsJNI.tiledb_error_tp_assign(SWIGTYPE_p_tiledb_error_t.getCPtr(obj), SWIGTYPE_p_tiledb_error_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_error_t tiledb_error_tp_value(SWIGTYPE_p_tiledb_error_t obj) {
    return new SWIGTYPE_p_tiledb_error_t(tiledbUtilsJNI.tiledb_error_tp_value(SWIGTYPE_p_tiledb_error_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_error_t new_tiledb_error_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_error_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_error_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_error_t copy_tiledb_error_tpp(SWIGTYPE_p_tiledb_error_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_error_tpp(SWIGTYPE_p_tiledb_error_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_error_t(cPtr, false);
  }

  public static void delete_tiledb_error_tpp(SWIGTYPE_p_p_tiledb_error_t obj) {
    tiledbUtilsJNI.delete_tiledb_error_tpp(SWIGTYPE_p_p_tiledb_error_t.getCPtr(obj));
  }

  public static void tiledb_error_tpp_assign(SWIGTYPE_p_p_tiledb_error_t obj, SWIGTYPE_p_tiledb_error_t value) {
    tiledbUtilsJNI.tiledb_error_tpp_assign(SWIGTYPE_p_p_tiledb_error_t.getCPtr(obj), SWIGTYPE_p_tiledb_error_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_error_t tiledb_error_tpp_value(SWIGTYPE_p_p_tiledb_error_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_error_tpp_value(SWIGTYPE_p_p_tiledb_error_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_error_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_attribute_t new_tiledb_attribute_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_attribute_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_attribute_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_attribute_t copy_tiledb_attribute_tp(SWIGTYPE_p_tiledb_attribute_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_attribute_tp(SWIGTYPE_p_tiledb_attribute_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_attribute_t(cPtr, false);
  }

  public static void delete_tiledb_attribute_tp(SWIGTYPE_p_tiledb_attribute_t obj) {
    tiledbUtilsJNI.delete_tiledb_attribute_tp(SWIGTYPE_p_tiledb_attribute_t.getCPtr(obj));
  }

  public static void tiledb_attribute_tp_assign(SWIGTYPE_p_tiledb_attribute_t obj, SWIGTYPE_p_tiledb_attribute_t value) {
    tiledbUtilsJNI.tiledb_attribute_tp_assign(SWIGTYPE_p_tiledb_attribute_t.getCPtr(obj), SWIGTYPE_p_tiledb_attribute_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_attribute_t tiledb_attribute_tp_value(SWIGTYPE_p_tiledb_attribute_t obj) {
    return new SWIGTYPE_p_tiledb_attribute_t(tiledbUtilsJNI.tiledb_attribute_tp_value(SWIGTYPE_p_tiledb_attribute_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_attribute_t new_tiledb_attribute_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_attribute_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_attribute_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_attribute_t copy_tiledb_attribute_tpp(SWIGTYPE_p_tiledb_attribute_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_attribute_tpp(SWIGTYPE_p_tiledb_attribute_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_attribute_t(cPtr, false);
  }

  public static void delete_tiledb_attribute_tpp(SWIGTYPE_p_p_tiledb_attribute_t obj) {
    tiledbUtilsJNI.delete_tiledb_attribute_tpp(SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(obj));
  }

  public static void tiledb_attribute_tpp_assign(SWIGTYPE_p_p_tiledb_attribute_t obj, SWIGTYPE_p_tiledb_attribute_t value) {
    tiledbUtilsJNI.tiledb_attribute_tpp_assign(SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(obj), SWIGTYPE_p_tiledb_attribute_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_attribute_t tiledb_attribute_tpp_value(SWIGTYPE_p_p_tiledb_attribute_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_attribute_tpp_value(SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_attribute_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_array_schema_t new_tiledb_array_schema_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_array_schema_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_array_schema_t copy_tiledb_array_schema_tp(SWIGTYPE_p_tiledb_array_schema_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_array_schema_tp(SWIGTYPE_p_tiledb_array_schema_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_schema_t(cPtr, false);
  }

  public static void delete_tiledb_array_schema_tp(SWIGTYPE_p_tiledb_array_schema_t obj) {
    tiledbUtilsJNI.delete_tiledb_array_schema_tp(SWIGTYPE_p_tiledb_array_schema_t.getCPtr(obj));
  }

  public static void tiledb_array_schema_tp_assign(SWIGTYPE_p_tiledb_array_schema_t obj, SWIGTYPE_p_tiledb_array_schema_t value) {
    tiledbUtilsJNI.tiledb_array_schema_tp_assign(SWIGTYPE_p_tiledb_array_schema_t.getCPtr(obj), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_array_schema_t tiledb_array_schema_tp_value(SWIGTYPE_p_tiledb_array_schema_t obj) {
    return new SWIGTYPE_p_tiledb_array_schema_t(tiledbUtilsJNI.tiledb_array_schema_tp_value(SWIGTYPE_p_tiledb_array_schema_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_array_schema_t new_tiledb_array_schema_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_array_schema_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_array_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_array_schema_t copy_tiledb_array_schema_tpp(SWIGTYPE_p_tiledb_array_schema_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_array_schema_tpp(SWIGTYPE_p_tiledb_array_schema_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_array_schema_t(cPtr, false);
  }

  public static void delete_tiledb_array_schema_tpp(SWIGTYPE_p_p_tiledb_array_schema_t obj) {
    tiledbUtilsJNI.delete_tiledb_array_schema_tpp(SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(obj));
  }

  public static void tiledb_array_schema_tpp_assign(SWIGTYPE_p_p_tiledb_array_schema_t obj, SWIGTYPE_p_tiledb_array_schema_t value) {
    tiledbUtilsJNI.tiledb_array_schema_tpp_assign(SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(obj), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_array_schema_t tiledb_array_schema_tpp_value(SWIGTYPE_p_p_tiledb_array_schema_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_array_schema_tpp_value(SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_dimension_t new_tiledb_dimension_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_dimension_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_dimension_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_dimension_t copy_tiledb_dimension_tp(SWIGTYPE_p_tiledb_dimension_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_dimension_tp(SWIGTYPE_p_tiledb_dimension_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_dimension_t(cPtr, false);
  }

  public static void delete_tiledb_dimension_tp(SWIGTYPE_p_tiledb_dimension_t obj) {
    tiledbUtilsJNI.delete_tiledb_dimension_tp(SWIGTYPE_p_tiledb_dimension_t.getCPtr(obj));
  }

  public static void tiledb_dimension_tp_assign(SWIGTYPE_p_tiledb_dimension_t obj, SWIGTYPE_p_tiledb_dimension_t value) {
    tiledbUtilsJNI.tiledb_dimension_tp_assign(SWIGTYPE_p_tiledb_dimension_t.getCPtr(obj), SWIGTYPE_p_tiledb_dimension_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_dimension_t tiledb_dimension_tp_value(SWIGTYPE_p_tiledb_dimension_t obj) {
    return new SWIGTYPE_p_tiledb_dimension_t(tiledbUtilsJNI.tiledb_dimension_tp_value(SWIGTYPE_p_tiledb_dimension_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_dimension_t new_tiledb_dimension_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_dimension_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_dimension_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_dimension_t copy_tiledb_dimension_tpp(SWIGTYPE_p_tiledb_dimension_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_dimension_tpp(SWIGTYPE_p_tiledb_dimension_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_dimension_t(cPtr, false);
  }

  public static void delete_tiledb_dimension_tpp(SWIGTYPE_p_p_tiledb_dimension_t obj) {
    tiledbUtilsJNI.delete_tiledb_dimension_tpp(SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(obj));
  }

  public static void tiledb_dimension_tpp_assign(SWIGTYPE_p_p_tiledb_dimension_t obj, SWIGTYPE_p_tiledb_dimension_t value) {
    tiledbUtilsJNI.tiledb_dimension_tpp_assign(SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(obj), SWIGTYPE_p_tiledb_dimension_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_dimension_t tiledb_dimension_tpp_value(SWIGTYPE_p_p_tiledb_dimension_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_dimension_tpp_value(SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_dimension_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_domain_t new_tiledb_domain_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_domain_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_domain_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_domain_t copy_tiledb_domain_tp(SWIGTYPE_p_tiledb_domain_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_domain_tp(SWIGTYPE_p_tiledb_domain_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_domain_t(cPtr, false);
  }

  public static void delete_tiledb_domain_tp(SWIGTYPE_p_tiledb_domain_t obj) {
    tiledbUtilsJNI.delete_tiledb_domain_tp(SWIGTYPE_p_tiledb_domain_t.getCPtr(obj));
  }

  public static void tiledb_domain_tp_assign(SWIGTYPE_p_tiledb_domain_t obj, SWIGTYPE_p_tiledb_domain_t value) {
    tiledbUtilsJNI.tiledb_domain_tp_assign(SWIGTYPE_p_tiledb_domain_t.getCPtr(obj), SWIGTYPE_p_tiledb_domain_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_domain_t tiledb_domain_tp_value(SWIGTYPE_p_tiledb_domain_t obj) {
    return new SWIGTYPE_p_tiledb_domain_t(tiledbUtilsJNI.tiledb_domain_tp_value(SWIGTYPE_p_tiledb_domain_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_domain_t new_tiledb_domain_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_domain_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_domain_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_domain_t copy_tiledb_domain_tpp(SWIGTYPE_p_tiledb_domain_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_domain_tpp(SWIGTYPE_p_tiledb_domain_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_domain_t(cPtr, false);
  }

  public static void delete_tiledb_domain_tpp(SWIGTYPE_p_p_tiledb_domain_t obj) {
    tiledbUtilsJNI.delete_tiledb_domain_tpp(SWIGTYPE_p_p_tiledb_domain_t.getCPtr(obj));
  }

  public static void tiledb_domain_tpp_assign(SWIGTYPE_p_p_tiledb_domain_t obj, SWIGTYPE_p_tiledb_domain_t value) {
    tiledbUtilsJNI.tiledb_domain_tpp_assign(SWIGTYPE_p_p_tiledb_domain_t.getCPtr(obj), SWIGTYPE_p_tiledb_domain_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_domain_t tiledb_domain_tpp_value(SWIGTYPE_p_p_tiledb_domain_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_domain_tpp_value(SWIGTYPE_p_p_tiledb_domain_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_domain_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_query_t new_tiledb_query_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_query_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_query_t copy_tiledb_query_tp(SWIGTYPE_p_tiledb_query_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_query_tp(SWIGTYPE_p_tiledb_query_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_t(cPtr, false);
  }

  public static void delete_tiledb_query_tp(SWIGTYPE_p_tiledb_query_t obj) {
    tiledbUtilsJNI.delete_tiledb_query_tp(SWIGTYPE_p_tiledb_query_t.getCPtr(obj));
  }

  public static void tiledb_query_tp_assign(SWIGTYPE_p_tiledb_query_t obj, SWIGTYPE_p_tiledb_query_t value) {
    tiledbUtilsJNI.tiledb_query_tp_assign(SWIGTYPE_p_tiledb_query_t.getCPtr(obj), SWIGTYPE_p_tiledb_query_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_query_t tiledb_query_tp_value(SWIGTYPE_p_tiledb_query_t obj) {
    return new SWIGTYPE_p_tiledb_query_t(tiledbUtilsJNI.tiledb_query_tp_value(SWIGTYPE_p_tiledb_query_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_query_t new_tiledb_query_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_query_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_query_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_query_t copy_tiledb_query_tpp(SWIGTYPE_p_tiledb_query_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_query_tpp(SWIGTYPE_p_tiledb_query_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_query_t(cPtr, false);
  }

  public static void delete_tiledb_query_tpp(SWIGTYPE_p_p_tiledb_query_t obj) {
    tiledbUtilsJNI.delete_tiledb_query_tpp(SWIGTYPE_p_p_tiledb_query_t.getCPtr(obj));
  }

  public static void tiledb_query_tpp_assign(SWIGTYPE_p_p_tiledb_query_t obj, SWIGTYPE_p_tiledb_query_t value) {
    tiledbUtilsJNI.tiledb_query_tpp_assign(SWIGTYPE_p_p_tiledb_query_t.getCPtr(obj), SWIGTYPE_p_tiledb_query_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_query_t tiledb_query_tpp_value(SWIGTYPE_p_p_tiledb_query_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_query_tpp_value(SWIGTYPE_p_p_tiledb_query_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_kv_schema_t new_tiledb_kv_schema_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_kv_schema_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_kv_schema_t copy_tiledb_kv_schema_tp(SWIGTYPE_p_tiledb_kv_schema_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_kv_schema_tp(SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_schema_t(cPtr, false);
  }

  public static void delete_tiledb_kv_schema_tp(SWIGTYPE_p_tiledb_kv_schema_t obj) {
    tiledbUtilsJNI.delete_tiledb_kv_schema_tp(SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(obj));
  }

  public static void tiledb_kv_schema_tp_assign(SWIGTYPE_p_tiledb_kv_schema_t obj, SWIGTYPE_p_tiledb_kv_schema_t value) {
    tiledbUtilsJNI.tiledb_kv_schema_tp_assign(SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_schema_t tiledb_kv_schema_tp_value(SWIGTYPE_p_tiledb_kv_schema_t obj) {
    return new SWIGTYPE_p_tiledb_kv_schema_t(tiledbUtilsJNI.tiledb_kv_schema_tp_value(SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_kv_schema_t new_tiledb_kv_schema_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_kv_schema_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_schema_t copy_tiledb_kv_schema_tpp(SWIGTYPE_p_tiledb_kv_schema_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_kv_schema_tpp(SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_schema_t(cPtr, false);
  }

  public static void delete_tiledb_kv_schema_tpp(SWIGTYPE_p_p_tiledb_kv_schema_t obj) {
    tiledbUtilsJNI.delete_tiledb_kv_schema_tpp(SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(obj));
  }

  public static void tiledb_kv_schema_tpp_assign(SWIGTYPE_p_p_tiledb_kv_schema_t obj, SWIGTYPE_p_tiledb_kv_schema_t value) {
    tiledbUtilsJNI.tiledb_kv_schema_tpp_assign(SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_schema_t tiledb_kv_schema_tpp_value(SWIGTYPE_p_p_tiledb_kv_schema_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_kv_schema_tpp_value(SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_kv_t new_tiledb_kv_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_kv_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_kv_t copy_tiledb_kv_tp(SWIGTYPE_p_tiledb_kv_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_kv_tp(SWIGTYPE_p_tiledb_kv_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_t(cPtr, false);
  }

  public static void delete_tiledb_kv_tp(SWIGTYPE_p_tiledb_kv_t obj) {
    tiledbUtilsJNI.delete_tiledb_kv_tp(SWIGTYPE_p_tiledb_kv_t.getCPtr(obj));
  }

  public static void tiledb_kv_tp_assign(SWIGTYPE_p_tiledb_kv_t obj, SWIGTYPE_p_tiledb_kv_t value) {
    tiledbUtilsJNI.tiledb_kv_tp_assign(SWIGTYPE_p_tiledb_kv_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_t tiledb_kv_tp_value(SWIGTYPE_p_tiledb_kv_t obj) {
    return new SWIGTYPE_p_tiledb_kv_t(tiledbUtilsJNI.tiledb_kv_tp_value(SWIGTYPE_p_tiledb_kv_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_kv_t new_tiledb_kv_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_kv_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_t copy_tiledb_kv_tpp(SWIGTYPE_p_tiledb_kv_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_kv_tpp(SWIGTYPE_p_tiledb_kv_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_t(cPtr, false);
  }

  public static void delete_tiledb_kv_tpp(SWIGTYPE_p_p_tiledb_kv_t obj) {
    tiledbUtilsJNI.delete_tiledb_kv_tpp(SWIGTYPE_p_p_tiledb_kv_t.getCPtr(obj));
  }

  public static void tiledb_kv_tpp_assign(SWIGTYPE_p_p_tiledb_kv_t obj, SWIGTYPE_p_tiledb_kv_t value) {
    tiledbUtilsJNI.tiledb_kv_tpp_assign(SWIGTYPE_p_p_tiledb_kv_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_t tiledb_kv_tpp_value(SWIGTYPE_p_p_tiledb_kv_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_kv_tpp_value(SWIGTYPE_p_p_tiledb_kv_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_kv_item_t new_tiledb_kv_item_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_kv_item_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_item_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_kv_item_t copy_tiledb_kv_item_tp(SWIGTYPE_p_tiledb_kv_item_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_kv_item_tp(SWIGTYPE_p_tiledb_kv_item_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_item_t(cPtr, false);
  }

  public static void delete_tiledb_kv_item_tp(SWIGTYPE_p_tiledb_kv_item_t obj) {
    tiledbUtilsJNI.delete_tiledb_kv_item_tp(SWIGTYPE_p_tiledb_kv_item_t.getCPtr(obj));
  }

  public static void tiledb_kv_item_tp_assign(SWIGTYPE_p_tiledb_kv_item_t obj, SWIGTYPE_p_tiledb_kv_item_t value) {
    tiledbUtilsJNI.tiledb_kv_item_tp_assign(SWIGTYPE_p_tiledb_kv_item_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_item_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_item_t tiledb_kv_item_tp_value(SWIGTYPE_p_tiledb_kv_item_t obj) {
    return new SWIGTYPE_p_tiledb_kv_item_t(tiledbUtilsJNI.tiledb_kv_item_tp_value(SWIGTYPE_p_tiledb_kv_item_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_kv_item_t new_tiledb_kv_item_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_kv_item_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_item_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_item_t copy_tiledb_kv_item_tpp(SWIGTYPE_p_tiledb_kv_item_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_kv_item_tpp(SWIGTYPE_p_tiledb_kv_item_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_item_t(cPtr, false);
  }

  public static void delete_tiledb_kv_item_tpp(SWIGTYPE_p_p_tiledb_kv_item_t obj) {
    tiledbUtilsJNI.delete_tiledb_kv_item_tpp(SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(obj));
  }

  public static void tiledb_kv_item_tpp_assign(SWIGTYPE_p_p_tiledb_kv_item_t obj, SWIGTYPE_p_tiledb_kv_item_t value) {
    tiledbUtilsJNI.tiledb_kv_item_tpp_assign(SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_item_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_item_t tiledb_kv_item_tpp_value(SWIGTYPE_p_p_tiledb_kv_item_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_kv_item_tpp_value(SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_item_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_kv_iter_t new_tiledb_kv_iter_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_kv_iter_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_kv_iter_t copy_tiledb_kv_iter_tp(SWIGTYPE_p_tiledb_kv_iter_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_kv_iter_tp(SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_iter_t(cPtr, false);
  }

  public static void delete_tiledb_kv_iter_tp(SWIGTYPE_p_tiledb_kv_iter_t obj) {
    tiledbUtilsJNI.delete_tiledb_kv_iter_tp(SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(obj));
  }

  public static void tiledb_kv_iter_tp_assign(SWIGTYPE_p_tiledb_kv_iter_t obj, SWIGTYPE_p_tiledb_kv_iter_t value) {
    tiledbUtilsJNI.tiledb_kv_iter_tp_assign(SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_iter_t tiledb_kv_iter_tp_value(SWIGTYPE_p_tiledb_kv_iter_t obj) {
    return new SWIGTYPE_p_tiledb_kv_iter_t(tiledbUtilsJNI.tiledb_kv_iter_tp_value(SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_kv_iter_t new_tiledb_kv_iter_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_kv_iter_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_iter_t copy_tiledb_kv_iter_tpp(SWIGTYPE_p_tiledb_kv_iter_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_kv_iter_tpp(SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_iter_t(cPtr, false);
  }

  public static void delete_tiledb_kv_iter_tpp(SWIGTYPE_p_p_tiledb_kv_iter_t obj) {
    tiledbUtilsJNI.delete_tiledb_kv_iter_tpp(SWIGTYPE_p_p_tiledb_kv_iter_t.getCPtr(obj));
  }

  public static void tiledb_kv_iter_tpp_assign(SWIGTYPE_p_p_tiledb_kv_iter_t obj, SWIGTYPE_p_tiledb_kv_iter_t value) {
    tiledbUtilsJNI.tiledb_kv_iter_tpp_assign(SWIGTYPE_p_p_tiledb_kv_iter_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_iter_t tiledb_kv_iter_tpp_value(SWIGTYPE_p_p_tiledb_kv_iter_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_kv_iter_tpp_value(SWIGTYPE_p_p_tiledb_kv_iter_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_vfs_t new_tiledb_vfs_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_vfs_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_vfs_t copy_tiledb_vfs_tp(SWIGTYPE_p_tiledb_vfs_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_vfs_tp(SWIGTYPE_p_tiledb_vfs_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_t(cPtr, false);
  }

  public static void delete_tiledb_vfs_tp(SWIGTYPE_p_tiledb_vfs_t obj) {
    tiledbUtilsJNI.delete_tiledb_vfs_tp(SWIGTYPE_p_tiledb_vfs_t.getCPtr(obj));
  }

  public static void tiledb_vfs_tp_assign(SWIGTYPE_p_tiledb_vfs_t obj, SWIGTYPE_p_tiledb_vfs_t value) {
    tiledbUtilsJNI.tiledb_vfs_tp_assign(SWIGTYPE_p_tiledb_vfs_t.getCPtr(obj), SWIGTYPE_p_tiledb_vfs_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_vfs_t tiledb_vfs_tp_value(SWIGTYPE_p_tiledb_vfs_t obj) {
    return new SWIGTYPE_p_tiledb_vfs_t(tiledbUtilsJNI.tiledb_vfs_tp_value(SWIGTYPE_p_tiledb_vfs_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_vfs_t new_tiledb_vfs_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_vfs_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_vfs_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_vfs_t copy_tiledb_vfs_tpp(SWIGTYPE_p_tiledb_vfs_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_vfs_tpp(SWIGTYPE_p_tiledb_vfs_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_vfs_t(cPtr, false);
  }

  public static void delete_tiledb_vfs_tpp(SWIGTYPE_p_p_tiledb_vfs_t obj) {
    tiledbUtilsJNI.delete_tiledb_vfs_tpp(SWIGTYPE_p_p_tiledb_vfs_t.getCPtr(obj));
  }

  public static void tiledb_vfs_tpp_assign(SWIGTYPE_p_p_tiledb_vfs_t obj, SWIGTYPE_p_tiledb_vfs_t value) {
    tiledbUtilsJNI.tiledb_vfs_tpp_assign(SWIGTYPE_p_p_tiledb_vfs_t.getCPtr(obj), SWIGTYPE_p_tiledb_vfs_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_vfs_t tiledb_vfs_tpp_value(SWIGTYPE_p_p_tiledb_vfs_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_vfs_tpp_value(SWIGTYPE_p_p_tiledb_vfs_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_vfs_fh_t new_tiledb_vfs_fh_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_vfs_fh_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_fh_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_vfs_fh_t copy_tiledb_vfs_fh_tp(SWIGTYPE_p_tiledb_vfs_fh_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_vfs_fh_tp(SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_fh_t(cPtr, false);
  }

  public static void delete_tiledb_vfs_fh_tp(SWIGTYPE_p_tiledb_vfs_fh_t obj) {
    tiledbUtilsJNI.delete_tiledb_vfs_fh_tp(SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(obj));
  }

  public static void tiledb_vfs_fh_tp_assign(SWIGTYPE_p_tiledb_vfs_fh_t obj, SWIGTYPE_p_tiledb_vfs_fh_t value) {
    tiledbUtilsJNI.tiledb_vfs_fh_tp_assign(SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(obj), SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_vfs_fh_t tiledb_vfs_fh_tp_value(SWIGTYPE_p_tiledb_vfs_fh_t obj) {
    return new SWIGTYPE_p_tiledb_vfs_fh_t(tiledbUtilsJNI.tiledb_vfs_fh_tp_value(SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_tiledb_vfs_fh_t new_tiledb_vfs_fh_tpp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_vfs_fh_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_vfs_fh_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_vfs_fh_t copy_tiledb_vfs_fh_tpp(SWIGTYPE_p_tiledb_vfs_fh_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_vfs_fh_tpp(SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_vfs_fh_t(cPtr, false);
  }

  public static void delete_tiledb_vfs_fh_tpp(SWIGTYPE_p_p_tiledb_vfs_fh_t obj) {
    tiledbUtilsJNI.delete_tiledb_vfs_fh_tpp(SWIGTYPE_p_p_tiledb_vfs_fh_t.getCPtr(obj));
  }

  public static void tiledb_vfs_fh_tpp_assign(SWIGTYPE_p_p_tiledb_vfs_fh_t obj, SWIGTYPE_p_tiledb_vfs_fh_t value) {
    tiledbUtilsJNI.tiledb_vfs_fh_tpp_assign(SWIGTYPE_p_p_tiledb_vfs_fh_t.getCPtr(obj), SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_vfs_fh_t tiledb_vfs_fh_tpp_value(SWIGTYPE_p_p_tiledb_vfs_fh_t obj) {
    long cPtr = tiledbUtilsJNI.tiledb_vfs_fh_tpp_value(SWIGTYPE_p_p_tiledb_vfs_fh_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_fh_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_object_t new_tiledb_object_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_object_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_object_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_object_t copy_tiledb_object_tp(SWIGTYPE_p_tiledb_object_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_object_tp(SWIGTYPE_p_tiledb_object_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_object_t(cPtr, false);
  }

  public static void delete_tiledb_object_tp(SWIGTYPE_p_tiledb_object_t obj) {
    tiledbUtilsJNI.delete_tiledb_object_tp(SWIGTYPE_p_tiledb_object_t.getCPtr(obj));
  }

  public static void tiledb_object_tp_assign(SWIGTYPE_p_tiledb_object_t obj, SWIGTYPE_p_tiledb_object_t value) {
    tiledbUtilsJNI.tiledb_object_tp_assign(SWIGTYPE_p_tiledb_object_t.getCPtr(obj), SWIGTYPE_p_tiledb_object_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_object_t tiledb_object_tp_value(SWIGTYPE_p_tiledb_object_t obj) {
    return new SWIGTYPE_p_tiledb_object_t(tiledbUtilsJNI.tiledb_object_tp_value(SWIGTYPE_p_tiledb_object_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_query_type_t new_tiledb_query_type_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_query_type_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_type_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_query_type_t copy_tiledb_query_type_tp(SWIGTYPE_p_tiledb_query_type_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_query_type_tp(SWIGTYPE_p_tiledb_query_type_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_type_t(cPtr, false);
  }

  public static void delete_tiledb_query_type_tp(SWIGTYPE_p_tiledb_query_type_t obj) {
    tiledbUtilsJNI.delete_tiledb_query_type_tp(SWIGTYPE_p_tiledb_query_type_t.getCPtr(obj));
  }

  public static void tiledb_query_type_tp_assign(SWIGTYPE_p_tiledb_query_type_t obj, SWIGTYPE_p_tiledb_query_type_t value) {
    tiledbUtilsJNI.tiledb_query_type_tp_assign(SWIGTYPE_p_tiledb_query_type_t.getCPtr(obj), SWIGTYPE_p_tiledb_query_type_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_query_type_t tiledb_query_type_tp_value(SWIGTYPE_p_tiledb_query_type_t obj) {
    return new SWIGTYPE_p_tiledb_query_type_t(tiledbUtilsJNI.tiledb_query_type_tp_value(SWIGTYPE_p_tiledb_query_type_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_query_status_t new_tiledb_query_status_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_query_status_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_status_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_query_status_t copy_tiledb_query_status_tp(SWIGTYPE_p_tiledb_query_status_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_query_status_tp(SWIGTYPE_p_tiledb_query_status_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_status_t(cPtr, false);
  }

  public static void delete_tiledb_query_status_tp(SWIGTYPE_p_tiledb_query_status_t obj) {
    tiledbUtilsJNI.delete_tiledb_query_status_tp(SWIGTYPE_p_tiledb_query_status_t.getCPtr(obj));
  }

  public static void tiledb_query_status_tp_assign(SWIGTYPE_p_tiledb_query_status_t obj, SWIGTYPE_p_tiledb_query_status_t value) {
    tiledbUtilsJNI.tiledb_query_status_tp_assign(SWIGTYPE_p_tiledb_query_status_t.getCPtr(obj), SWIGTYPE_p_tiledb_query_status_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_query_status_t tiledb_query_status_tp_value(SWIGTYPE_p_tiledb_query_status_t obj) {
    return new SWIGTYPE_p_tiledb_query_status_t(tiledbUtilsJNI.tiledb_query_status_tp_value(SWIGTYPE_p_tiledb_query_status_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_filesystem_t new_tiledb_filesystem_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_filesystem_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_filesystem_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_filesystem_t copy_tiledb_filesystem_tp(SWIGTYPE_p_tiledb_filesystem_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_filesystem_tp(SWIGTYPE_p_tiledb_filesystem_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_filesystem_t(cPtr, false);
  }

  public static void delete_tiledb_filesystem_tp(SWIGTYPE_p_tiledb_filesystem_t obj) {
    tiledbUtilsJNI.delete_tiledb_filesystem_tp(SWIGTYPE_p_tiledb_filesystem_t.getCPtr(obj));
  }

  public static void tiledb_filesystem_tp_assign(SWIGTYPE_p_tiledb_filesystem_t obj, SWIGTYPE_p_tiledb_filesystem_t value) {
    tiledbUtilsJNI.tiledb_filesystem_tp_assign(SWIGTYPE_p_tiledb_filesystem_t.getCPtr(obj), SWIGTYPE_p_tiledb_filesystem_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_filesystem_t tiledb_filesystem_tp_value(SWIGTYPE_p_tiledb_filesystem_t obj) {
    return new SWIGTYPE_p_tiledb_filesystem_t(tiledbUtilsJNI.tiledb_filesystem_tp_value(SWIGTYPE_p_tiledb_filesystem_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_datatype_t new_tiledb_datatype_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_datatype_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_datatype_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_datatype_t copy_tiledb_datatype_tp(SWIGTYPE_p_tiledb_datatype_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_datatype_tp(SWIGTYPE_p_tiledb_datatype_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_datatype_t(cPtr, false);
  }

  public static void delete_tiledb_datatype_tp(SWIGTYPE_p_tiledb_datatype_t obj) {
    tiledbUtilsJNI.delete_tiledb_datatype_tp(SWIGTYPE_p_tiledb_datatype_t.getCPtr(obj));
  }

  public static void tiledb_datatype_tp_assign(SWIGTYPE_p_tiledb_datatype_t obj, SWIGTYPE_p_tiledb_datatype_t value) {
    tiledbUtilsJNI.tiledb_datatype_tp_assign(SWIGTYPE_p_tiledb_datatype_t.getCPtr(obj), SWIGTYPE_p_tiledb_datatype_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_datatype_t tiledb_datatype_tp_value(SWIGTYPE_p_tiledb_datatype_t obj) {
    return new SWIGTYPE_p_tiledb_datatype_t(tiledbUtilsJNI.tiledb_datatype_tp_value(SWIGTYPE_p_tiledb_datatype_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_array_type_t new_tiledb_array_type_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_array_type_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_type_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_array_type_t copy_tiledb_array_type_tp(SWIGTYPE_p_tiledb_array_type_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_array_type_tp(SWIGTYPE_p_tiledb_array_type_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_type_t(cPtr, false);
  }

  public static void delete_tiledb_array_type_tp(SWIGTYPE_p_tiledb_array_type_t obj) {
    tiledbUtilsJNI.delete_tiledb_array_type_tp(SWIGTYPE_p_tiledb_array_type_t.getCPtr(obj));
  }

  public static void tiledb_array_type_tp_assign(SWIGTYPE_p_tiledb_array_type_t obj, SWIGTYPE_p_tiledb_array_type_t value) {
    tiledbUtilsJNI.tiledb_array_type_tp_assign(SWIGTYPE_p_tiledb_array_type_t.getCPtr(obj), SWIGTYPE_p_tiledb_array_type_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_array_type_t tiledb_array_type_tp_value(SWIGTYPE_p_tiledb_array_type_t obj) {
    return new SWIGTYPE_p_tiledb_array_type_t(tiledbUtilsJNI.tiledb_array_type_tp_value(SWIGTYPE_p_tiledb_array_type_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_layout_t new_tiledb_layout_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_layout_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_layout_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_layout_t copy_tiledb_layout_tp(SWIGTYPE_p_tiledb_layout_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_layout_tp(SWIGTYPE_p_tiledb_layout_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_layout_t(cPtr, false);
  }

  public static void delete_tiledb_layout_tp(SWIGTYPE_p_tiledb_layout_t obj) {
    tiledbUtilsJNI.delete_tiledb_layout_tp(SWIGTYPE_p_tiledb_layout_t.getCPtr(obj));
  }

  public static void tiledb_layout_tp_assign(SWIGTYPE_p_tiledb_layout_t obj, SWIGTYPE_p_tiledb_layout_t value) {
    tiledbUtilsJNI.tiledb_layout_tp_assign(SWIGTYPE_p_tiledb_layout_t.getCPtr(obj), SWIGTYPE_p_tiledb_layout_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_layout_t tiledb_layout_tp_value(SWIGTYPE_p_tiledb_layout_t obj) {
    return new SWIGTYPE_p_tiledb_layout_t(tiledbUtilsJNI.tiledb_layout_tp_value(SWIGTYPE_p_tiledb_layout_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_compressor_t new_tiledb_compressor_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_compressor_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_compressor_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_compressor_t copy_tiledb_compressor_tp(SWIGTYPE_p_tiledb_compressor_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_compressor_tp(SWIGTYPE_p_tiledb_compressor_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_compressor_t(cPtr, false);
  }

  public static void delete_tiledb_compressor_tp(SWIGTYPE_p_tiledb_compressor_t obj) {
    tiledbUtilsJNI.delete_tiledb_compressor_tp(SWIGTYPE_p_tiledb_compressor_t.getCPtr(obj));
  }

  public static void tiledb_compressor_tp_assign(SWIGTYPE_p_tiledb_compressor_t obj, SWIGTYPE_p_tiledb_compressor_t value) {
    tiledbUtilsJNI.tiledb_compressor_tp_assign(SWIGTYPE_p_tiledb_compressor_t.getCPtr(obj), SWIGTYPE_p_tiledb_compressor_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_compressor_t tiledb_compressor_tp_value(SWIGTYPE_p_tiledb_compressor_t obj) {
    return new SWIGTYPE_p_tiledb_compressor_t(tiledbUtilsJNI.tiledb_compressor_tp_value(SWIGTYPE_p_tiledb_compressor_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_walk_order_t new_tiledb_walk_order_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_walk_order_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_walk_order_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_walk_order_t copy_tiledb_walk_order_tp(SWIGTYPE_p_tiledb_walk_order_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_walk_order_tp(SWIGTYPE_p_tiledb_walk_order_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_walk_order_t(cPtr, false);
  }

  public static void delete_tiledb_walk_order_tp(SWIGTYPE_p_tiledb_walk_order_t obj) {
    tiledbUtilsJNI.delete_tiledb_walk_order_tp(SWIGTYPE_p_tiledb_walk_order_t.getCPtr(obj));
  }

  public static void tiledb_walk_order_tp_assign(SWIGTYPE_p_tiledb_walk_order_t obj, SWIGTYPE_p_tiledb_walk_order_t value) {
    tiledbUtilsJNI.tiledb_walk_order_tp_assign(SWIGTYPE_p_tiledb_walk_order_t.getCPtr(obj), SWIGTYPE_p_tiledb_walk_order_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_walk_order_t tiledb_walk_order_tp_value(SWIGTYPE_p_tiledb_walk_order_t obj) {
    return new SWIGTYPE_p_tiledb_walk_order_t(tiledbUtilsJNI.tiledb_walk_order_tp_value(SWIGTYPE_p_tiledb_walk_order_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_tiledb_vfs_mode_t new_tiledb_vfs_mode_tp() {
    long cPtr = tiledbUtilsJNI.new_tiledb_vfs_mode_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_mode_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_vfs_mode_t copy_tiledb_vfs_mode_tp(SWIGTYPE_p_tiledb_vfs_mode_t value) {
    long cPtr = tiledbUtilsJNI.copy_tiledb_vfs_mode_tp(SWIGTYPE_p_tiledb_vfs_mode_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_mode_t(cPtr, false);
  }

  public static void delete_tiledb_vfs_mode_tp(SWIGTYPE_p_tiledb_vfs_mode_t obj) {
    tiledbUtilsJNI.delete_tiledb_vfs_mode_tp(SWIGTYPE_p_tiledb_vfs_mode_t.getCPtr(obj));
  }

  public static void tiledb_vfs_mode_tp_assign(SWIGTYPE_p_tiledb_vfs_mode_t obj, SWIGTYPE_p_tiledb_vfs_mode_t value) {
    tiledbUtilsJNI.tiledb_vfs_mode_tp_assign(SWIGTYPE_p_tiledb_vfs_mode_t.getCPtr(obj), SWIGTYPE_p_tiledb_vfs_mode_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_vfs_mode_t tiledb_vfs_mode_tp_value(SWIGTYPE_p_tiledb_vfs_mode_t obj) {
    return new SWIGTYPE_p_tiledb_vfs_mode_t(tiledbUtilsJNI.tiledb_vfs_mode_tp_value(SWIGTYPE_p_tiledb_vfs_mode_t.getCPtr(obj)), true);
  }

}
