/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.api;

public interface tiledbConstants {
  public final static int TILEDB_OK = 0;
  public final static int TILEDB_ERR = (-1);
  public final static int TILEDB_OOM = (-2);
}
