/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public class __mbstate_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __mbstate_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__mbstate_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete___mbstate_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__mbstate8(String value) {
    tiledbJNI.__mbstate_t___mbstate8_set(swigCPtr, this, value);
  }

  public String get__mbstate8() {
    return tiledbJNI.__mbstate_t___mbstate8_get(swigCPtr, this);
  }

  public void set_mbstateL(long value) {
    tiledbJNI.__mbstate_t__mbstateL_set(swigCPtr, this, value);
  }

  public long get_mbstateL() {
    return tiledbJNI.__mbstate_t__mbstateL_get(swigCPtr, this);
  }

  public __mbstate_t() {
    this(tiledbJNI.new___mbstate_t(), true);
  }
}
