/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public class capi_return_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected capi_return_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(capi_return_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(capi_return_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete_capi_return_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public capi_return_t(long nelements) {
    this(tiledbJNI.new_capi_return_t(nelements), true);
  }

  public capi_return_t getitem(long index) {
    return new capi_return_t(tiledbJNI.capi_return_t_getitem(swigCPtr, this, index), true);
  }

  public void setitem(long index, capi_return_t value) {
    tiledbJNI.capi_return_t_setitem(swigCPtr, this, index, capi_return_t.getCPtr(value), value);
  }

  public capi_return_t cast() {
    long cPtr = tiledbJNI.capi_return_t_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new capi_return_t(cPtr, false);
  }

  public static capi_return_t frompointer(capi_return_t t) {
    long cPtr = tiledbJNI.capi_return_t_frompointer(capi_return_t.getCPtr(t), t);
    return (cPtr == 0) ? null : new capi_return_t(cPtr, false);
  }
}
