/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public class charArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;
  private final int nelements;

  protected charArray(long cPtr, boolean cMemoryOwn, int nelements) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
    this.nelements = nelements;
  }

  protected static long getCPtr(charArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete_charArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public charArray(int nelements) {
    this(tiledbJNI.new_charArray(nelements), true, nelements);
  }

  public char getitem(int index) {
    if (index >= nelements || index < 0) {
      throw new ArrayIndexOutOfBoundsException(index);
    }
    return tiledbJNI.charArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, char value) {
    if (index >= nelements || index < 0) {
      throw new ArrayIndexOutOfBoundsException(index);
    }
    tiledbJNI.charArray_setitem(swigCPtr, this, index, value);
  }

  public String cast() {
    return tiledbJNI.charArray_cast(swigCPtr, this);
  }

  protected int size() {
    return nelements;
  }
}
