/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public class charArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected charArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(charArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(charArray obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete_charArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public charArray(long nelements) {
    this(tiledbJNI.new_charArray(nelements), true);
  }

  public char getitem(long index) {
    return tiledbJNI.charArray_getitem(swigCPtr, this, index);
  }

  public void setitem(long index, char value) {
    tiledbJNI.charArray_setitem(swigCPtr, this, index, value);
  }

  public String cast() {
    return tiledbJNI.charArray_cast(swigCPtr, this);
  }

  public static charArray frompointer(String t) {
    long cPtr = tiledbJNI.charArray_frompointer(t);
    return (cPtr == 0) ? null : new charArray(cPtr, false);
  }

}
