/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public abstract class PathCallback {
  private int call(long path, int type, int nelements) {
    charArray jpath = new charArray(path, false, nelements);
    tiledb_object_t jtype = tiledb_object_t.swigToEnum(type);
    return call(Utils.charArrayGet(jpath, 0), jtype);
  }

  public abstract int call(String path, tiledb_object_t type);
}
