/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public class tiledb_range_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public tiledb_range_t(long cPtr, boolean cMemoryOwn) { // todo
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tiledb_range_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(tiledb_range_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tiledbJNI.delete_tiledb_range_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMin(SWIGTYPE_p_void value) {
    tiledbJNI.tiledb_range_t_min_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getMin() {
    long cPtr = tiledbJNI.tiledb_range_t_min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setMin_size(java.math.BigInteger value) {
    tiledbJNI.tiledb_range_t_min_size_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getMin_size() {
    return tiledbJNI.tiledb_range_t_min_size_get(swigCPtr, this);
  }

  public void setMax(SWIGTYPE_p_void value) {
    tiledbJNI.tiledb_range_t_max_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getMax() {
    long cPtr = tiledbJNI.tiledb_range_t_max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setMax_size(java.math.BigInteger value) {
    tiledbJNI.tiledb_range_t_max_size_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getMax_size() {
    return tiledbJNI.tiledb_range_t_max_size_get(swigCPtr, this);
  }

  public tiledb_range_t() {
    this(tiledbJNI.new_tiledb_range_t(), true);
  }
}
