/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public interface tiledbConstants {
  public final static int TILEDB_VERSION_MINOR = 5;
  public final static int TILEDB_VERSION_MAJOR = 1;
  public final static int TILEDB_VERSION_PATCH = 0;
  public final static int TILEDB_OOM = (-2);
  public final static int TILEDB_OK = 0;
  public final static int TILEDB_ERR = (-1);
}
