/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public interface tiledbConstants {
  public static final int TILEDB_VERSION_MINOR = 6;
  public static final int TILEDB_VERSION_MAJOR = 1;
  public static final int TILEDB_VERSION_PATCH = 0;
  public static final int TILEDB_OOM = (-2);
  public static final int TILEDB_OK = 0;
  public static final int TILEDB_ERR = (-1);
}
