/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public class tiledb implements tiledbConstants {
  public static SWIGTYPE_p_p_char new_charpArray(int nelements) {
    long cPtr = tiledbJNI.new_charpArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static void delete_charpArray(SWIGTYPE_p_p_char ary) {
    tiledbJNI.delete_charpArray(SWIGTYPE_p_p_char.getCPtr(ary));
  }

  public static String charpArray_getitem(SWIGTYPE_p_p_char ary, int index) {
    return tiledbJNI.charpArray_getitem(SWIGTYPE_p_p_char.getCPtr(ary), index);
  }

  public static void charpArray_setitem(SWIGTYPE_p_p_char ary, int index, String value) {
    tiledbJNI.charpArray_setitem(SWIGTYPE_p_p_char.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_p_void new_voidpArray(int nelements) {
    long cPtr = tiledbJNI.new_voidpArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public static void delete_voidpArray(SWIGTYPE_p_p_void ary) {
    tiledbJNI.delete_voidpArray(SWIGTYPE_p_p_void.getCPtr(ary));
  }

  public static SWIGTYPE_p_void voidpArray_getitem(SWIGTYPE_p_p_void ary, int index) {
    long cPtr = tiledbJNI.voidpArray_getitem(SWIGTYPE_p_p_void.getCPtr(ary), index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void voidpArray_setitem(SWIGTYPE_p_p_void ary, int index, SWIGTYPE_p_void value) {
    tiledbJNI.voidpArray_setitem(SWIGTYPE_p_p_void.getCPtr(ary), index, SWIGTYPE_p_void.getCPtr(value));
  }

  public static SWIGTYPE_p_int new_intp() {
    long cPtr = tiledbJNI.new_intp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    long cPtr = tiledbJNI.copy_intp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    tiledbJNI.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    tiledbJNI.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    return tiledbJNI.intp_value(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static SWIGTYPE_p_float new_floatp() {
    long cPtr = tiledbJNI.new_floatp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static SWIGTYPE_p_float copy_floatp(float value) {
    long cPtr = tiledbJNI.copy_floatp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static void delete_floatp(SWIGTYPE_p_float obj) {
    tiledbJNI.delete_floatp(SWIGTYPE_p_float.getCPtr(obj));
  }

  public static void floatp_assign(SWIGTYPE_p_float obj, float value) {
    tiledbJNI.floatp_assign(SWIGTYPE_p_float.getCPtr(obj), value);
  }

  public static float floatp_value(SWIGTYPE_p_float obj) {
    return tiledbJNI.floatp_value(SWIGTYPE_p_float.getCPtr(obj));
  }

  public static SWIGTYPE_p_p_p_void new_voidppp() {
    long cPtr = tiledbJNI.new_voidppp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_p_p_void copy_voidppp(SWIGTYPE_p_p_void value) {
    long cPtr = tiledbJNI.copy_voidppp(SWIGTYPE_p_p_void.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_void(cPtr, false);
  }

  public static void delete_voidppp(SWIGTYPE_p_p_p_void obj) {
    tiledbJNI.delete_voidppp(SWIGTYPE_p_p_p_void.getCPtr(obj));
  }

  public static void voidppp_assign(SWIGTYPE_p_p_p_void obj, SWIGTYPE_p_p_void value) {
    tiledbJNI.voidppp_assign(SWIGTYPE_p_p_p_void.getCPtr(obj), SWIGTYPE_p_p_void.getCPtr(value));
  }

  public static SWIGTYPE_p_p_void voidppp_value(SWIGTYPE_p_p_p_void obj) {
    long cPtr = tiledbJNI.voidppp_value(SWIGTYPE_p_p_p_void.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_p_int new_intpp() {
    long cPtr = tiledbJNI.new_intpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_p_int copy_intpp(SWIGTYPE_p_int value) {
    long cPtr = tiledbJNI.copy_intpp(SWIGTYPE_p_int.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_int(cPtr, false);
  }

  public static void delete_intpp(SWIGTYPE_p_p_int obj) {
    tiledbJNI.delete_intpp(SWIGTYPE_p_p_int.getCPtr(obj));
  }

  public static void intpp_assign(SWIGTYPE_p_p_int obj, SWIGTYPE_p_int value) {
    tiledbJNI.intpp_assign(SWIGTYPE_p_p_int.getCPtr(obj), SWIGTYPE_p_int.getCPtr(value));
  }

  public static SWIGTYPE_p_int intpp_value(SWIGTYPE_p_p_int obj) {
    long cPtr = tiledbJNI.intpp_value(SWIGTYPE_p_p_int.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_p_char new_charpp() {
    long cPtr = tiledbJNI.new_charpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static SWIGTYPE_p_p_char copy_charpp(String value) {
    long cPtr = tiledbJNI.copy_charpp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static void delete_charpp(SWIGTYPE_p_p_char obj) {
    tiledbJNI.delete_charpp(SWIGTYPE_p_p_char.getCPtr(obj));
  }

  public static void charpp_assign(SWIGTYPE_p_p_char obj, String value) {
    tiledbJNI.charpp_assign(SWIGTYPE_p_p_char.getCPtr(obj), value);
  }

  public static String charpp_value(SWIGTYPE_p_p_char obj) {
    return tiledbJNI.charpp_value(SWIGTYPE_p_p_char.getCPtr(obj));
  }

  public static SWIGTYPE_p_unsigned_int new_uintp() {
    long cPtr = tiledbJNI.new_uintp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_int copy_uintp(long value) {
    long cPtr = tiledbJNI.copy_uintp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public static void delete_uintp(SWIGTYPE_p_unsigned_int obj) {
    tiledbJNI.delete_uintp(SWIGTYPE_p_unsigned_int.getCPtr(obj));
  }

  public static void uintp_assign(SWIGTYPE_p_unsigned_int obj, long value) {
    tiledbJNI.uintp_assign(SWIGTYPE_p_unsigned_int.getCPtr(obj), value);
  }

  public static long uintp_value(SWIGTYPE_p_unsigned_int obj) {
    return tiledbJNI.uintp_value(SWIGTYPE_p_unsigned_int.getCPtr(obj));
  }

  public static SWIGTYPE_p_unsigned_long_long new_ullp() {
    long cPtr = tiledbJNI.new_ullp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_long_long copy_ullp(java.math.BigInteger value) {
    long cPtr = tiledbJNI.copy_ullp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public static void delete_ullp(SWIGTYPE_p_unsigned_long_long obj) {
    tiledbJNI.delete_ullp(SWIGTYPE_p_unsigned_long_long.getCPtr(obj));
  }

  public static void ullp_assign(SWIGTYPE_p_unsigned_long_long obj, java.math.BigInteger value) {
    tiledbJNI.ullp_assign(SWIGTYPE_p_unsigned_long_long.getCPtr(obj), value);
  }

  public static java.math.BigInteger ullp_value(SWIGTYPE_p_unsigned_long_long obj) {
    return tiledbJNI.ullp_value(SWIGTYPE_p_unsigned_long_long.getCPtr(obj));
  }

  public static SWIGTYPE_p_tiledb_object_t new_tiledb_object_tp() {
    long cPtr = tiledbJNI.new_tiledb_object_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_object_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_object_t copy_tiledb_object_tp(tiledb_object_t value) {
    long cPtr = tiledbJNI.copy_tiledb_object_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_object_t(cPtr, false);
  }

  public static void delete_tiledb_object_tp(SWIGTYPE_p_tiledb_object_t obj) {
    tiledbJNI.delete_tiledb_object_tp(SWIGTYPE_p_tiledb_object_t.getCPtr(obj));
  }

  public static void tiledb_object_tp_assign(SWIGTYPE_p_tiledb_object_t obj, tiledb_object_t value) {
    tiledbJNI.tiledb_object_tp_assign(SWIGTYPE_p_tiledb_object_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_object_t tiledb_object_tp_value(SWIGTYPE_p_tiledb_object_t obj) {
    return tiledb_object_t.swigToEnum(tiledbJNI.tiledb_object_tp_value(SWIGTYPE_p_tiledb_object_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_query_type_t new_tiledb_query_type_tp() {
    long cPtr = tiledbJNI.new_tiledb_query_type_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_type_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_query_type_t copy_tiledb_query_type_tp(tiledb_query_type_t value) {
    long cPtr = tiledbJNI.copy_tiledb_query_type_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_type_t(cPtr, false);
  }

  public static void delete_tiledb_query_type_tp(SWIGTYPE_p_tiledb_query_type_t obj) {
    tiledbJNI.delete_tiledb_query_type_tp(SWIGTYPE_p_tiledb_query_type_t.getCPtr(obj));
  }

  public static void tiledb_query_type_tp_assign(SWIGTYPE_p_tiledb_query_type_t obj, tiledb_query_type_t value) {
    tiledbJNI.tiledb_query_type_tp_assign(SWIGTYPE_p_tiledb_query_type_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_query_type_t tiledb_query_type_tp_value(SWIGTYPE_p_tiledb_query_type_t obj) {
    return tiledb_query_type_t.swigToEnum(tiledbJNI.tiledb_query_type_tp_value(SWIGTYPE_p_tiledb_query_type_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_query_status_t new_tiledb_query_status_tp() {
    long cPtr = tiledbJNI.new_tiledb_query_status_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_status_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_query_status_t copy_tiledb_query_status_tp(tiledb_query_status_t value) {
    long cPtr = tiledbJNI.copy_tiledb_query_status_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_status_t(cPtr, false);
  }

  public static void delete_tiledb_query_status_tp(SWIGTYPE_p_tiledb_query_status_t obj) {
    tiledbJNI.delete_tiledb_query_status_tp(SWIGTYPE_p_tiledb_query_status_t.getCPtr(obj));
  }

  public static void tiledb_query_status_tp_assign(SWIGTYPE_p_tiledb_query_status_t obj, tiledb_query_status_t value) {
    tiledbJNI.tiledb_query_status_tp_assign(SWIGTYPE_p_tiledb_query_status_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_query_status_t tiledb_query_status_tp_value(SWIGTYPE_p_tiledb_query_status_t obj) {
    return tiledb_query_status_t.swigToEnum(tiledbJNI.tiledb_query_status_tp_value(SWIGTYPE_p_tiledb_query_status_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_filesystem_t new_tiledb_filesystem_tp() {
    long cPtr = tiledbJNI.new_tiledb_filesystem_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_filesystem_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_filesystem_t copy_tiledb_filesystem_tp(tiledb_filesystem_t value) {
    long cPtr = tiledbJNI.copy_tiledb_filesystem_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_filesystem_t(cPtr, false);
  }

  public static void delete_tiledb_filesystem_tp(SWIGTYPE_p_tiledb_filesystem_t obj) {
    tiledbJNI.delete_tiledb_filesystem_tp(SWIGTYPE_p_tiledb_filesystem_t.getCPtr(obj));
  }

  public static void tiledb_filesystem_tp_assign(SWIGTYPE_p_tiledb_filesystem_t obj, tiledb_filesystem_t value) {
    tiledbJNI.tiledb_filesystem_tp_assign(SWIGTYPE_p_tiledb_filesystem_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_filesystem_t tiledb_filesystem_tp_value(SWIGTYPE_p_tiledb_filesystem_t obj) {
    return tiledb_filesystem_t.swigToEnum(tiledbJNI.tiledb_filesystem_tp_value(SWIGTYPE_p_tiledb_filesystem_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_datatype_t new_tiledb_datatype_tp() {
    long cPtr = tiledbJNI.new_tiledb_datatype_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_datatype_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_datatype_t copy_tiledb_datatype_tp(tiledb_datatype_t value) {
    long cPtr = tiledbJNI.copy_tiledb_datatype_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_datatype_t(cPtr, false);
  }

  public static void delete_tiledb_datatype_tp(SWIGTYPE_p_tiledb_datatype_t obj) {
    tiledbJNI.delete_tiledb_datatype_tp(SWIGTYPE_p_tiledb_datatype_t.getCPtr(obj));
  }

  public static void tiledb_datatype_tp_assign(SWIGTYPE_p_tiledb_datatype_t obj, tiledb_datatype_t value) {
    tiledbJNI.tiledb_datatype_tp_assign(SWIGTYPE_p_tiledb_datatype_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_datatype_t tiledb_datatype_tp_value(SWIGTYPE_p_tiledb_datatype_t obj) {
    return tiledb_datatype_t.swigToEnum(tiledbJNI.tiledb_datatype_tp_value(SWIGTYPE_p_tiledb_datatype_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_array_type_t new_tiledb_array_type_tp() {
    long cPtr = tiledbJNI.new_tiledb_array_type_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_type_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_array_type_t copy_tiledb_array_type_tp(tiledb_array_type_t value) {
    long cPtr = tiledbJNI.copy_tiledb_array_type_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_type_t(cPtr, false);
  }

  public static void delete_tiledb_array_type_tp(SWIGTYPE_p_tiledb_array_type_t obj) {
    tiledbJNI.delete_tiledb_array_type_tp(SWIGTYPE_p_tiledb_array_type_t.getCPtr(obj));
  }

  public static void tiledb_array_type_tp_assign(SWIGTYPE_p_tiledb_array_type_t obj, tiledb_array_type_t value) {
    tiledbJNI.tiledb_array_type_tp_assign(SWIGTYPE_p_tiledb_array_type_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_array_type_t tiledb_array_type_tp_value(SWIGTYPE_p_tiledb_array_type_t obj) {
    return tiledb_array_type_t.swigToEnum(tiledbJNI.tiledb_array_type_tp_value(SWIGTYPE_p_tiledb_array_type_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_layout_t new_tiledb_layout_tp() {
    long cPtr = tiledbJNI.new_tiledb_layout_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_layout_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_layout_t copy_tiledb_layout_tp(tiledb_layout_t value) {
    long cPtr = tiledbJNI.copy_tiledb_layout_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_layout_t(cPtr, false);
  }

  public static void delete_tiledb_layout_tp(SWIGTYPE_p_tiledb_layout_t obj) {
    tiledbJNI.delete_tiledb_layout_tp(SWIGTYPE_p_tiledb_layout_t.getCPtr(obj));
  }

  public static void tiledb_layout_tp_assign(SWIGTYPE_p_tiledb_layout_t obj, tiledb_layout_t value) {
    tiledbJNI.tiledb_layout_tp_assign(SWIGTYPE_p_tiledb_layout_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_layout_t tiledb_layout_tp_value(SWIGTYPE_p_tiledb_layout_t obj) {
    return tiledb_layout_t.swigToEnum(tiledbJNI.tiledb_layout_tp_value(SWIGTYPE_p_tiledb_layout_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_compressor_t new_tiledb_compressor_tp() {
    long cPtr = tiledbJNI.new_tiledb_compressor_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_compressor_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_compressor_t copy_tiledb_compressor_tp(tiledb_compressor_t value) {
    long cPtr = tiledbJNI.copy_tiledb_compressor_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_compressor_t(cPtr, false);
  }

  public static void delete_tiledb_compressor_tp(SWIGTYPE_p_tiledb_compressor_t obj) {
    tiledbJNI.delete_tiledb_compressor_tp(SWIGTYPE_p_tiledb_compressor_t.getCPtr(obj));
  }

  public static void tiledb_compressor_tp_assign(SWIGTYPE_p_tiledb_compressor_t obj, tiledb_compressor_t value) {
    tiledbJNI.tiledb_compressor_tp_assign(SWIGTYPE_p_tiledb_compressor_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_compressor_t tiledb_compressor_tp_value(SWIGTYPE_p_tiledb_compressor_t obj) {
    return tiledb_compressor_t.swigToEnum(tiledbJNI.tiledb_compressor_tp_value(SWIGTYPE_p_tiledb_compressor_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_walk_order_t new_tiledb_walk_order_tp() {
    long cPtr = tiledbJNI.new_tiledb_walk_order_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_walk_order_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_walk_order_t copy_tiledb_walk_order_tp(tiledb_walk_order_t value) {
    long cPtr = tiledbJNI.copy_tiledb_walk_order_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_walk_order_t(cPtr, false);
  }

  public static void delete_tiledb_walk_order_tp(SWIGTYPE_p_tiledb_walk_order_t obj) {
    tiledbJNI.delete_tiledb_walk_order_tp(SWIGTYPE_p_tiledb_walk_order_t.getCPtr(obj));
  }

  public static void tiledb_walk_order_tp_assign(SWIGTYPE_p_tiledb_walk_order_t obj, tiledb_walk_order_t value) {
    tiledbJNI.tiledb_walk_order_tp_assign(SWIGTYPE_p_tiledb_walk_order_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_walk_order_t tiledb_walk_order_tp_value(SWIGTYPE_p_tiledb_walk_order_t obj) {
    return tiledb_walk_order_t.swigToEnum(tiledbJNI.tiledb_walk_order_tp_value(SWIGTYPE_p_tiledb_walk_order_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_tiledb_vfs_mode_t new_tiledb_vfs_mode_tp() {
    long cPtr = tiledbJNI.new_tiledb_vfs_mode_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_mode_t(cPtr, false);
  }

  public static SWIGTYPE_p_tiledb_vfs_mode_t copy_tiledb_vfs_mode_tp(tiledb_vfs_mode_t value) {
    long cPtr = tiledbJNI.copy_tiledb_vfs_mode_tp(value.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_mode_t(cPtr, false);
  }

  public static void delete_tiledb_vfs_mode_tp(SWIGTYPE_p_tiledb_vfs_mode_t obj) {
    tiledbJNI.delete_tiledb_vfs_mode_tp(SWIGTYPE_p_tiledb_vfs_mode_t.getCPtr(obj));
  }

  public static void tiledb_vfs_mode_tp_assign(SWIGTYPE_p_tiledb_vfs_mode_t obj, tiledb_vfs_mode_t value) {
    tiledbJNI.tiledb_vfs_mode_tp_assign(SWIGTYPE_p_tiledb_vfs_mode_t.getCPtr(obj), value.swigValue());
  }

  public static tiledb_vfs_mode_t tiledb_vfs_mode_tp_value(SWIGTYPE_p_tiledb_vfs_mode_t obj) {
    return tiledb_vfs_mode_t.swigToEnum(tiledbJNI.tiledb_vfs_mode_tp_value(SWIGTYPE_p_tiledb_vfs_mode_t.getCPtr(obj)));
  }

  public static SWIGTYPE_p_p_tiledb_array_t new_tiledb_array_tpp() {
    long cPtr = tiledbJNI.new_tiledb_array_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_array_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_array_t copy_tiledb_array_tpp(SWIGTYPE_p_tiledb_array_t value) {
    long cPtr = tiledbJNI.copy_tiledb_array_tpp(SWIGTYPE_p_tiledb_array_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_array_t(cPtr, false);
  }

  public static void delete_tiledb_array_tpp(SWIGTYPE_p_p_tiledb_array_t obj) {
    tiledbJNI.delete_tiledb_array_tpp(SWIGTYPE_p_p_tiledb_array_t.getCPtr(obj));
  }

  public static void tiledb_array_tpp_assign(SWIGTYPE_p_p_tiledb_array_t obj, SWIGTYPE_p_tiledb_array_t value) {
    tiledbJNI.tiledb_array_tpp_assign(SWIGTYPE_p_p_tiledb_array_t.getCPtr(obj), SWIGTYPE_p_tiledb_array_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_array_t tiledb_array_tpp_value(SWIGTYPE_p_p_tiledb_array_t obj) {
    long cPtr = tiledbJNI.tiledb_array_tpp_value(SWIGTYPE_p_p_tiledb_array_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_config_t new_tiledb_config_tpp() {
    long cPtr = tiledbJNI.new_tiledb_config_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_config_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_config_t copy_tiledb_config_tpp(SWIGTYPE_p_tiledb_config_t value) {
    long cPtr = tiledbJNI.copy_tiledb_config_tpp(SWIGTYPE_p_tiledb_config_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_config_t(cPtr, false);
  }

  public static void delete_tiledb_config_tpp(SWIGTYPE_p_p_tiledb_config_t obj) {
    tiledbJNI.delete_tiledb_config_tpp(SWIGTYPE_p_p_tiledb_config_t.getCPtr(obj));
  }

  public static void tiledb_config_tpp_assign(SWIGTYPE_p_p_tiledb_config_t obj, SWIGTYPE_p_tiledb_config_t value) {
    tiledbJNI.tiledb_config_tpp_assign(SWIGTYPE_p_p_tiledb_config_t.getCPtr(obj), SWIGTYPE_p_tiledb_config_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_config_t tiledb_config_tpp_value(SWIGTYPE_p_p_tiledb_config_t obj) {
    long cPtr = tiledbJNI.tiledb_config_tpp_value(SWIGTYPE_p_p_tiledb_config_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_config_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_config_iter_t new_tiledb_config_iter_tpp() {
    long cPtr = tiledbJNI.new_tiledb_config_iter_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_config_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_config_iter_t copy_tiledb_config_iter_tpp(SWIGTYPE_p_tiledb_config_iter_t value) {
    long cPtr = tiledbJNI.copy_tiledb_config_iter_tpp(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_config_iter_t(cPtr, false);
  }

  public static void delete_tiledb_config_iter_tpp(SWIGTYPE_p_p_tiledb_config_iter_t obj) {
    tiledbJNI.delete_tiledb_config_iter_tpp(SWIGTYPE_p_p_tiledb_config_iter_t.getCPtr(obj));
  }

  public static void tiledb_config_iter_tpp_assign(SWIGTYPE_p_p_tiledb_config_iter_t obj, SWIGTYPE_p_tiledb_config_iter_t value) {
    tiledbJNI.tiledb_config_iter_tpp_assign(SWIGTYPE_p_p_tiledb_config_iter_t.getCPtr(obj), SWIGTYPE_p_tiledb_config_iter_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_config_iter_t tiledb_config_iter_tpp_value(SWIGTYPE_p_p_tiledb_config_iter_t obj) {
    long cPtr = tiledbJNI.tiledb_config_iter_tpp_value(SWIGTYPE_p_p_tiledb_config_iter_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_config_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_ctx_t new_tiledb_ctx_tpp() {
    long cPtr = tiledbJNI.new_tiledb_ctx_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_ctx_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_ctx_t copy_tiledb_ctx_tpp(SWIGTYPE_p_tiledb_ctx_t value) {
    long cPtr = tiledbJNI.copy_tiledb_ctx_tpp(SWIGTYPE_p_tiledb_ctx_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_ctx_t(cPtr, false);
  }

  public static void delete_tiledb_ctx_tpp(SWIGTYPE_p_p_tiledb_ctx_t obj) {
    tiledbJNI.delete_tiledb_ctx_tpp(SWIGTYPE_p_p_tiledb_ctx_t.getCPtr(obj));
  }

  public static void tiledb_ctx_tpp_assign(SWIGTYPE_p_p_tiledb_ctx_t obj, SWIGTYPE_p_tiledb_ctx_t value) {
    tiledbJNI.tiledb_ctx_tpp_assign(SWIGTYPE_p_p_tiledb_ctx_t.getCPtr(obj), SWIGTYPE_p_tiledb_ctx_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_ctx_t tiledb_ctx_tpp_value(SWIGTYPE_p_p_tiledb_ctx_t obj) {
    long cPtr = tiledbJNI.tiledb_ctx_tpp_value(SWIGTYPE_p_p_tiledb_ctx_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_ctx_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_error_t new_tiledb_error_tpp() {
    long cPtr = tiledbJNI.new_tiledb_error_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_error_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_error_t copy_tiledb_error_tpp(SWIGTYPE_p_tiledb_error_t value) {
    long cPtr = tiledbJNI.copy_tiledb_error_tpp(SWIGTYPE_p_tiledb_error_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_error_t(cPtr, false);
  }

  public static void delete_tiledb_error_tpp(SWIGTYPE_p_p_tiledb_error_t obj) {
    tiledbJNI.delete_tiledb_error_tpp(SWIGTYPE_p_p_tiledb_error_t.getCPtr(obj));
  }

  public static void tiledb_error_tpp_assign(SWIGTYPE_p_p_tiledb_error_t obj, SWIGTYPE_p_tiledb_error_t value) {
    tiledbJNI.tiledb_error_tpp_assign(SWIGTYPE_p_p_tiledb_error_t.getCPtr(obj), SWIGTYPE_p_tiledb_error_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_error_t tiledb_error_tpp_value(SWIGTYPE_p_p_tiledb_error_t obj) {
    long cPtr = tiledbJNI.tiledb_error_tpp_value(SWIGTYPE_p_p_tiledb_error_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_error_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_attribute_t new_tiledb_attribute_tpp() {
    long cPtr = tiledbJNI.new_tiledb_attribute_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_attribute_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_attribute_t copy_tiledb_attribute_tpp(SWIGTYPE_p_tiledb_attribute_t value) {
    long cPtr = tiledbJNI.copy_tiledb_attribute_tpp(SWIGTYPE_p_tiledb_attribute_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_attribute_t(cPtr, false);
  }

  public static void delete_tiledb_attribute_tpp(SWIGTYPE_p_p_tiledb_attribute_t obj) {
    tiledbJNI.delete_tiledb_attribute_tpp(SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(obj));
  }

  public static void tiledb_attribute_tpp_assign(SWIGTYPE_p_p_tiledb_attribute_t obj, SWIGTYPE_p_tiledb_attribute_t value) {
    tiledbJNI.tiledb_attribute_tpp_assign(SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(obj), SWIGTYPE_p_tiledb_attribute_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_attribute_t tiledb_attribute_tpp_value(SWIGTYPE_p_p_tiledb_attribute_t obj) {
    long cPtr = tiledbJNI.tiledb_attribute_tpp_value(SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_attribute_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_array_schema_t new_tiledb_array_schema_tpp() {
    long cPtr = tiledbJNI.new_tiledb_array_schema_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_array_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_array_schema_t copy_tiledb_array_schema_tpp(SWIGTYPE_p_tiledb_array_schema_t value) {
    long cPtr = tiledbJNI.copy_tiledb_array_schema_tpp(SWIGTYPE_p_tiledb_array_schema_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_array_schema_t(cPtr, false);
  }

  public static void delete_tiledb_array_schema_tpp(SWIGTYPE_p_p_tiledb_array_schema_t obj) {
    tiledbJNI.delete_tiledb_array_schema_tpp(SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(obj));
  }

  public static void tiledb_array_schema_tpp_assign(SWIGTYPE_p_p_tiledb_array_schema_t obj, SWIGTYPE_p_tiledb_array_schema_t value) {
    tiledbJNI.tiledb_array_schema_tpp_assign(SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(obj), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_array_schema_t tiledb_array_schema_tpp_value(SWIGTYPE_p_p_tiledb_array_schema_t obj) {
    long cPtr = tiledbJNI.tiledb_array_schema_tpp_value(SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_array_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_dimension_t new_tiledb_dimension_tpp() {
    long cPtr = tiledbJNI.new_tiledb_dimension_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_dimension_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_dimension_t copy_tiledb_dimension_tpp(SWIGTYPE_p_tiledb_dimension_t value) {
    long cPtr = tiledbJNI.copy_tiledb_dimension_tpp(SWIGTYPE_p_tiledb_dimension_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_dimension_t(cPtr, false);
  }

  public static void delete_tiledb_dimension_tpp(SWIGTYPE_p_p_tiledb_dimension_t obj) {
    tiledbJNI.delete_tiledb_dimension_tpp(SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(obj));
  }

  public static void tiledb_dimension_tpp_assign(SWIGTYPE_p_p_tiledb_dimension_t obj, SWIGTYPE_p_tiledb_dimension_t value) {
    tiledbJNI.tiledb_dimension_tpp_assign(SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(obj), SWIGTYPE_p_tiledb_dimension_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_dimension_t tiledb_dimension_tpp_value(SWIGTYPE_p_p_tiledb_dimension_t obj) {
    long cPtr = tiledbJNI.tiledb_dimension_tpp_value(SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_dimension_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_domain_t new_tiledb_domain_tpp() {
    long cPtr = tiledbJNI.new_tiledb_domain_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_domain_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_domain_t copy_tiledb_domain_tpp(SWIGTYPE_p_tiledb_domain_t value) {
    long cPtr = tiledbJNI.copy_tiledb_domain_tpp(SWIGTYPE_p_tiledb_domain_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_domain_t(cPtr, false);
  }

  public static void delete_tiledb_domain_tpp(SWIGTYPE_p_p_tiledb_domain_t obj) {
    tiledbJNI.delete_tiledb_domain_tpp(SWIGTYPE_p_p_tiledb_domain_t.getCPtr(obj));
  }

  public static void tiledb_domain_tpp_assign(SWIGTYPE_p_p_tiledb_domain_t obj, SWIGTYPE_p_tiledb_domain_t value) {
    tiledbJNI.tiledb_domain_tpp_assign(SWIGTYPE_p_p_tiledb_domain_t.getCPtr(obj), SWIGTYPE_p_tiledb_domain_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_domain_t tiledb_domain_tpp_value(SWIGTYPE_p_p_tiledb_domain_t obj) {
    long cPtr = tiledbJNI.tiledb_domain_tpp_value(SWIGTYPE_p_p_tiledb_domain_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_domain_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_query_t new_tiledb_query_tpp() {
    long cPtr = tiledbJNI.new_tiledb_query_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_query_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_query_t copy_tiledb_query_tpp(SWIGTYPE_p_tiledb_query_t value) {
    long cPtr = tiledbJNI.copy_tiledb_query_tpp(SWIGTYPE_p_tiledb_query_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_query_t(cPtr, false);
  }

  public static void delete_tiledb_query_tpp(SWIGTYPE_p_p_tiledb_query_t obj) {
    tiledbJNI.delete_tiledb_query_tpp(SWIGTYPE_p_p_tiledb_query_t.getCPtr(obj));
  }

  public static void tiledb_query_tpp_assign(SWIGTYPE_p_p_tiledb_query_t obj, SWIGTYPE_p_tiledb_query_t value) {
    tiledbJNI.tiledb_query_tpp_assign(SWIGTYPE_p_p_tiledb_query_t.getCPtr(obj), SWIGTYPE_p_tiledb_query_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_query_t tiledb_query_tpp_value(SWIGTYPE_p_p_tiledb_query_t obj) {
    long cPtr = tiledbJNI.tiledb_query_tpp_value(SWIGTYPE_p_p_tiledb_query_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_query_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_schema_t new_tiledb_kv_schema_tpp() {
    long cPtr = tiledbJNI.new_tiledb_kv_schema_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_schema_t copy_tiledb_kv_schema_tpp(SWIGTYPE_p_tiledb_kv_schema_t value) {
    long cPtr = tiledbJNI.copy_tiledb_kv_schema_tpp(SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_schema_t(cPtr, false);
  }

  public static void delete_tiledb_kv_schema_tpp(SWIGTYPE_p_p_tiledb_kv_schema_t obj) {
    tiledbJNI.delete_tiledb_kv_schema_tpp(SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(obj));
  }

  public static void tiledb_kv_schema_tpp_assign(SWIGTYPE_p_p_tiledb_kv_schema_t obj, SWIGTYPE_p_tiledb_kv_schema_t value) {
    tiledbJNI.tiledb_kv_schema_tpp_assign(SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_schema_t tiledb_kv_schema_tpp_value(SWIGTYPE_p_p_tiledb_kv_schema_t obj) {
    long cPtr = tiledbJNI.tiledb_kv_schema_tpp_value(SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_schema_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_t new_tiledb_kv_tpp() {
    long cPtr = tiledbJNI.new_tiledb_kv_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_t copy_tiledb_kv_tpp(SWIGTYPE_p_tiledb_kv_t value) {
    long cPtr = tiledbJNI.copy_tiledb_kv_tpp(SWIGTYPE_p_tiledb_kv_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_t(cPtr, false);
  }

  public static void delete_tiledb_kv_tpp(SWIGTYPE_p_p_tiledb_kv_t obj) {
    tiledbJNI.delete_tiledb_kv_tpp(SWIGTYPE_p_p_tiledb_kv_t.getCPtr(obj));
  }

  public static void tiledb_kv_tpp_assign(SWIGTYPE_p_p_tiledb_kv_t obj, SWIGTYPE_p_tiledb_kv_t value) {
    tiledbJNI.tiledb_kv_tpp_assign(SWIGTYPE_p_p_tiledb_kv_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_t tiledb_kv_tpp_value(SWIGTYPE_p_p_tiledb_kv_t obj) {
    long cPtr = tiledbJNI.tiledb_kv_tpp_value(SWIGTYPE_p_p_tiledb_kv_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_item_t new_tiledb_kv_item_tpp() {
    long cPtr = tiledbJNI.new_tiledb_kv_item_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_item_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_item_t copy_tiledb_kv_item_tpp(SWIGTYPE_p_tiledb_kv_item_t value) {
    long cPtr = tiledbJNI.copy_tiledb_kv_item_tpp(SWIGTYPE_p_tiledb_kv_item_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_item_t(cPtr, false);
  }

  public static void delete_tiledb_kv_item_tpp(SWIGTYPE_p_p_tiledb_kv_item_t obj) {
    tiledbJNI.delete_tiledb_kv_item_tpp(SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(obj));
  }

  public static void tiledb_kv_item_tpp_assign(SWIGTYPE_p_p_tiledb_kv_item_t obj, SWIGTYPE_p_tiledb_kv_item_t value) {
    tiledbJNI.tiledb_kv_item_tpp_assign(SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_item_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_item_t tiledb_kv_item_tpp_value(SWIGTYPE_p_p_tiledb_kv_item_t obj) {
    long cPtr = tiledbJNI.tiledb_kv_item_tpp_value(SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_item_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_iter_t new_tiledb_kv_iter_tpp() {
    long cPtr = tiledbJNI.new_tiledb_kv_iter_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_kv_iter_t copy_tiledb_kv_iter_tpp(SWIGTYPE_p_tiledb_kv_iter_t value) {
    long cPtr = tiledbJNI.copy_tiledb_kv_iter_tpp(SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_kv_iter_t(cPtr, false);
  }

  public static void delete_tiledb_kv_iter_tpp(SWIGTYPE_p_p_tiledb_kv_iter_t obj) {
    tiledbJNI.delete_tiledb_kv_iter_tpp(SWIGTYPE_p_p_tiledb_kv_iter_t.getCPtr(obj));
  }

  public static void tiledb_kv_iter_tpp_assign(SWIGTYPE_p_p_tiledb_kv_iter_t obj, SWIGTYPE_p_tiledb_kv_iter_t value) {
    tiledbJNI.tiledb_kv_iter_tpp_assign(SWIGTYPE_p_p_tiledb_kv_iter_t.getCPtr(obj), SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_kv_iter_t tiledb_kv_iter_tpp_value(SWIGTYPE_p_p_tiledb_kv_iter_t obj) {
    long cPtr = tiledbJNI.tiledb_kv_iter_tpp_value(SWIGTYPE_p_p_tiledb_kv_iter_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_kv_iter_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_vfs_t new_tiledb_vfs_tpp() {
    long cPtr = tiledbJNI.new_tiledb_vfs_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_vfs_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_vfs_t copy_tiledb_vfs_tpp(SWIGTYPE_p_tiledb_vfs_t value) {
    long cPtr = tiledbJNI.copy_tiledb_vfs_tpp(SWIGTYPE_p_tiledb_vfs_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_vfs_t(cPtr, false);
  }

  public static void delete_tiledb_vfs_tpp(SWIGTYPE_p_p_tiledb_vfs_t obj) {
    tiledbJNI.delete_tiledb_vfs_tpp(SWIGTYPE_p_p_tiledb_vfs_t.getCPtr(obj));
  }

  public static void tiledb_vfs_tpp_assign(SWIGTYPE_p_p_tiledb_vfs_t obj, SWIGTYPE_p_tiledb_vfs_t value) {
    tiledbJNI.tiledb_vfs_tpp_assign(SWIGTYPE_p_p_tiledb_vfs_t.getCPtr(obj), SWIGTYPE_p_tiledb_vfs_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_vfs_t tiledb_vfs_tpp_value(SWIGTYPE_p_p_tiledb_vfs_t obj) {
    long cPtr = tiledbJNI.tiledb_vfs_tpp_value(SWIGTYPE_p_p_tiledb_vfs_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_vfs_fh_t new_tiledb_vfs_fh_tpp() {
    long cPtr = tiledbJNI.new_tiledb_vfs_fh_tpp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_vfs_fh_t(cPtr, false);
  }

  public static SWIGTYPE_p_p_tiledb_vfs_fh_t copy_tiledb_vfs_fh_tpp(SWIGTYPE_p_tiledb_vfs_fh_t value) {
    long cPtr = tiledbJNI.copy_tiledb_vfs_fh_tpp(SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_tiledb_vfs_fh_t(cPtr, false);
  }

  public static void delete_tiledb_vfs_fh_tpp(SWIGTYPE_p_p_tiledb_vfs_fh_t obj) {
    tiledbJNI.delete_tiledb_vfs_fh_tpp(SWIGTYPE_p_p_tiledb_vfs_fh_t.getCPtr(obj));
  }

  public static void tiledb_vfs_fh_tpp_assign(SWIGTYPE_p_p_tiledb_vfs_fh_t obj, SWIGTYPE_p_tiledb_vfs_fh_t value) {
    tiledbJNI.tiledb_vfs_fh_tpp_assign(SWIGTYPE_p_p_tiledb_vfs_fh_t.getCPtr(obj), SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(value));
  }

  public static SWIGTYPE_p_tiledb_vfs_fh_t tiledb_vfs_fh_tpp_value(SWIGTYPE_p_p_tiledb_vfs_fh_t obj) {
    long cPtr = tiledbJNI.tiledb_vfs_fh_tpp_value(SWIGTYPE_p_p_tiledb_vfs_fh_t.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_tiledb_vfs_fh_t(cPtr, false);
  }

  public static int sizeOfInt32() {
    return tiledbJNI.sizeOfInt32();
  }

  public static int sizeOfInt64() {
    return tiledbJNI.sizeOfInt64();
  }

  public static int sizeOfChar() {
    return tiledbJNI.sizeOfChar();
  }

  public static int sizeOfFloat() {
    return tiledbJNI.sizeOfFloat();
  }

  public static int sizeOfDouble() {
    return tiledbJNI.sizeOfDouble();
  }

  public static int sizeOfInt8() {
    return tiledbJNI.sizeOfInt8();
  }

  public static int sizeOfUint8() {
    return tiledbJNI.sizeOfUint8();
  }

  public static int sizeOfInt16() {
    return tiledbJNI.sizeOfInt16();
  }

  public static int sizeOfUint16() {
    return tiledbJNI.sizeOfUint16();
  }

  public static int sizeOfUint32() {
    return tiledbJNI.sizeOfUint32();
  }

  public static int sizeOfUint64() {
    return tiledbJNI.sizeOfUint64();
  }

  public static long newInt32ArraySet(int[] jarg1) {
    return tiledbJNI.newInt32ArraySet(jarg1);
  }

  public static long newInt64ArraySet(long[] jarg1) {
    return tiledbJNI.newInt64ArraySet(jarg1);
  }

  public static long newCharArraySet(String jarg1) {
    return tiledbJNI.newCharArraySet(jarg1);
  }

  public static long newFloatArraySet(float[] jarg1) {
    return tiledbJNI.newFloatArraySet(jarg1);
  }

  public static long newDoubleArraySet(double[] jarg1) {
    return tiledbJNI.newDoubleArraySet(jarg1);
  }

  public static long newInt8ArraySet(byte[] jarg1) {
    return tiledbJNI.newInt8ArraySet(jarg1);
  }

  public static long newUint8ArraySet(short[] jarg1) {
    return tiledbJNI.newUint8ArraySet(jarg1);
  }

  public static long newInt16ArraySet(short[] jarg1) {
    return tiledbJNI.newInt16ArraySet(jarg1);
  }

  public static long newUint16ArraySet(int[] jarg1) {
    return tiledbJNI.newUint16ArraySet(jarg1);
  }

  public static long newUint32ArraySet(long[] jarg1) {
    return tiledbJNI.newUint32ArraySet(jarg1);
  }

  public static long newUint64ArraySet(long[] jarg1) {
    return tiledbJNI.newUint64ArraySet(jarg1);
  }

  public static int[] int32ArrayGet(long array, int sz) {
    return tiledbJNI.int32ArrayGet(array, sz);
  }

  public static long[] int64ArrayGet(long array, int sz) {
    return tiledbJNI.int64ArrayGet(array, sz);
  }

  public static String charArrayGet(long array) {
    return tiledbJNI.charArrayGet(array);
  }

  public static float[] floatArrayGet(long array, int size) {
    return tiledbJNI.floatArrayGet(array, size);
  }

  public static double[] doubleArrayGet(long array, int size) {
    return tiledbJNI.doubleArrayGet(array, size);
  }

  public static byte[] int8ArrayGet(long array, int size) {
    return tiledbJNI.int8ArrayGet(array, size);
  }

  public static short[] uint8ArrayGet(long array, int size) {
    return tiledbJNI.uint8ArrayGet(array, size);
  }

  public static short[] int16ArrayGet(long array, int size) {
    return tiledbJNI.int16ArrayGet(array, size);
  }

  public static int[] uint16ArrayGet(long array, int size) {
    return tiledbJNI.uint16ArrayGet(array, size);
  }

  public static long[] uint32ArrayGet(long array, int size) {
    return tiledbJNI.uint32ArrayGet(array, size);
  }

  public static long[] uint64ArrayGet(long array, int size) {
    return tiledbJNI.uint64ArrayGet(array, size);
  }

  public static String tiledb_coords() {
    return tiledbJNI.tiledb_coords();
  }

  public static long tiledb_var_num() {
    return tiledbJNI.tiledb_var_num();
  }

  public static long tiledb_max_path() {
    return tiledbJNI.tiledb_max_path();
  }

  public static java.math.BigInteger tiledb_datatype_size(tiledb_datatype_t type) {
    return tiledbJNI.tiledb_datatype_size(type.swigValue());
  }

  public static java.math.BigInteger tiledb_offset_size() {
    return tiledbJNI.tiledb_offset_size();
  }

  public static void tiledb_version(SWIGTYPE_p_int major, SWIGTYPE_p_int minor, SWIGTYPE_p_int rev) {
    tiledbJNI.tiledb_version(SWIGTYPE_p_int.getCPtr(major), SWIGTYPE_p_int.getCPtr(minor), SWIGTYPE_p_int.getCPtr(rev));
  }

  public static int tiledb_error_message(SWIGTYPE_p_tiledb_error_t err, SWIGTYPE_p_p_char errmsg) {
    return tiledbJNI.tiledb_error_message(SWIGTYPE_p_tiledb_error_t.getCPtr(err), SWIGTYPE_p_p_char.getCPtr(errmsg));
  }

  public static void tiledb_error_free(SWIGTYPE_p_p_tiledb_error_t err) {
    tiledbJNI.tiledb_error_free(SWIGTYPE_p_p_tiledb_error_t.getCPtr(err));
  }

  public static int tiledb_config_alloc(SWIGTYPE_p_p_tiledb_config_t config, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_alloc(SWIGTYPE_p_p_tiledb_config_t.getCPtr(config), SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static void tiledb_config_free(SWIGTYPE_p_p_tiledb_config_t config) {
    tiledbJNI.tiledb_config_free(SWIGTYPE_p_p_tiledb_config_t.getCPtr(config));
  }

  public static int tiledb_config_set(SWIGTYPE_p_tiledb_config_t config, String param, String value, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_set(SWIGTYPE_p_tiledb_config_t.getCPtr(config), param, value, SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_config_get(SWIGTYPE_p_tiledb_config_t config, String param, SWIGTYPE_p_p_char value, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_get(SWIGTYPE_p_tiledb_config_t.getCPtr(config), param, SWIGTYPE_p_p_char.getCPtr(value), SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_config_load_from_file(SWIGTYPE_p_tiledb_config_t config, String filename, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_load_from_file(SWIGTYPE_p_tiledb_config_t.getCPtr(config), filename, SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_config_unset(SWIGTYPE_p_tiledb_config_t config, String param, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_unset(SWIGTYPE_p_tiledb_config_t.getCPtr(config), param, SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_config_save_to_file(SWIGTYPE_p_tiledb_config_t config, String filename, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_save_to_file(SWIGTYPE_p_tiledb_config_t.getCPtr(config), filename, SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_config_iter_alloc(SWIGTYPE_p_tiledb_config_t config, String prefix, SWIGTYPE_p_p_tiledb_config_iter_t config_iter, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_iter_alloc(SWIGTYPE_p_tiledb_config_t.getCPtr(config), prefix, SWIGTYPE_p_p_tiledb_config_iter_t.getCPtr(config_iter), SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_config_iter_reset(SWIGTYPE_p_tiledb_config_t config, SWIGTYPE_p_tiledb_config_iter_t config_iter, String prefix, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_iter_reset(SWIGTYPE_p_tiledb_config_t.getCPtr(config), SWIGTYPE_p_tiledb_config_iter_t.getCPtr(config_iter), prefix, SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static void tiledb_config_iter_free(SWIGTYPE_p_p_tiledb_config_iter_t config_iter) {
    tiledbJNI.tiledb_config_iter_free(SWIGTYPE_p_p_tiledb_config_iter_t.getCPtr(config_iter));
  }

  public static int tiledb_config_iter_here(SWIGTYPE_p_tiledb_config_iter_t config_iter, SWIGTYPE_p_p_char param, SWIGTYPE_p_p_char value, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_iter_here(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(config_iter), SWIGTYPE_p_p_char.getCPtr(param), SWIGTYPE_p_p_char.getCPtr(value), SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_config_iter_next(SWIGTYPE_p_tiledb_config_iter_t config_iter, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_iter_next(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(config_iter), SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_config_iter_done(SWIGTYPE_p_tiledb_config_iter_t config_iter, SWIGTYPE_p_int done, SWIGTYPE_p_p_tiledb_error_t error) {
    return tiledbJNI.tiledb_config_iter_done(SWIGTYPE_p_tiledb_config_iter_t.getCPtr(config_iter), SWIGTYPE_p_int.getCPtr(done), SWIGTYPE_p_p_tiledb_error_t.getCPtr(error));
  }

  public static int tiledb_ctx_alloc(SWIGTYPE_p_tiledb_config_t config, SWIGTYPE_p_p_tiledb_ctx_t ctx) {
    return tiledbJNI.tiledb_ctx_alloc(SWIGTYPE_p_tiledb_config_t.getCPtr(config), SWIGTYPE_p_p_tiledb_ctx_t.getCPtr(ctx));
  }

  public static void tiledb_ctx_free(SWIGTYPE_p_p_tiledb_ctx_t ctx) {
    tiledbJNI.tiledb_ctx_free(SWIGTYPE_p_p_tiledb_ctx_t.getCPtr(ctx));
  }

  public static int tiledb_ctx_get_config(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_p_tiledb_config_t config) {
    return tiledbJNI.tiledb_ctx_get_config(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_p_tiledb_config_t.getCPtr(config));
  }

  public static int tiledb_ctx_get_last_error(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_p_tiledb_error_t err) {
    return tiledbJNI.tiledb_ctx_get_last_error(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_p_tiledb_error_t.getCPtr(err));
  }

  public static int tiledb_ctx_is_supported_fs(SWIGTYPE_p_tiledb_ctx_t ctx, tiledb_filesystem_t fs, SWIGTYPE_p_int is_supported) {
    return tiledbJNI.tiledb_ctx_is_supported_fs(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), fs.swigValue(), SWIGTYPE_p_int.getCPtr(is_supported));
  }

  public static int tiledb_ctx_cancel_tasks(SWIGTYPE_p_tiledb_ctx_t ctx) {
    return tiledbJNI.tiledb_ctx_cancel_tasks(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx));
  }

  public static int tiledb_group_create(SWIGTYPE_p_tiledb_ctx_t ctx, String group_uri) {
    return tiledbJNI.tiledb_group_create(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), group_uri);
  }

  public static int tiledb_attribute_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, String name, tiledb_datatype_t type, SWIGTYPE_p_p_tiledb_attribute_t attr) {
    return tiledbJNI.tiledb_attribute_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), name, type.swigValue(), SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static void tiledb_attribute_free(SWIGTYPE_p_p_tiledb_attribute_t attr) {
    tiledbJNI.tiledb_attribute_free(SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static int tiledb_attribute_set_compressor(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, tiledb_compressor_t compressor, int compression_level) {
    return tiledbJNI.tiledb_attribute_set_compressor(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), compressor.swigValue(), compression_level);
  }

  public static int tiledb_attribute_set_cell_val_num(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, long cell_val_num) {
    return tiledbJNI.tiledb_attribute_set_cell_val_num(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), cell_val_num);
  }

  public static int tiledb_attribute_get_name(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, SWIGTYPE_p_p_char name) {
    return tiledbJNI.tiledb_attribute_get_name(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), SWIGTYPE_p_p_char.getCPtr(name));
  }

  public static int tiledb_attribute_get_type(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, SWIGTYPE_p_tiledb_datatype_t type) {
    return tiledbJNI.tiledb_attribute_get_type(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), SWIGTYPE_p_tiledb_datatype_t.getCPtr(type));
  }

  public static int tiledb_attribute_get_compressor(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, SWIGTYPE_p_tiledb_compressor_t compressor, SWIGTYPE_p_int compression_level) {
    return tiledbJNI.tiledb_attribute_get_compressor(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), SWIGTYPE_p_tiledb_compressor_t.getCPtr(compressor), SWIGTYPE_p_int.getCPtr(compression_level));
  }

  public static int tiledb_attribute_get_cell_val_num(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, SWIGTYPE_p_unsigned_int cell_val_num) {
    return tiledbJNI.tiledb_attribute_get_cell_val_num(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), SWIGTYPE_p_unsigned_int.getCPtr(cell_val_num));
  }

  public static int tiledb_attribute_get_cell_size(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, SWIGTYPE_p_unsigned_long_long cell_size) {
    return tiledbJNI.tiledb_attribute_get_cell_size(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), SWIGTYPE_p_unsigned_long_long.getCPtr(cell_size));
  }

  public static int tiledb_attribute_dump(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, SWIGTYPE_p_FILE out) {
    return tiledbJNI.tiledb_attribute_dump(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), SWIGTYPE_p_FILE.getCPtr(out));
  }

  public static int tiledb_domain_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_p_tiledb_domain_t domain) {
    return tiledbJNI.tiledb_domain_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_p_tiledb_domain_t.getCPtr(domain));
  }

  public static void tiledb_domain_free(SWIGTYPE_p_p_tiledb_domain_t domain) {
    tiledbJNI.tiledb_domain_free(SWIGTYPE_p_p_tiledb_domain_t.getCPtr(domain));
  }

  public static int tiledb_domain_get_type(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_domain_t domain, SWIGTYPE_p_tiledb_datatype_t type) {
    return tiledbJNI.tiledb_domain_get_type(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain), SWIGTYPE_p_tiledb_datatype_t.getCPtr(type));
  }

  public static int tiledb_domain_get_ndim(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_domain_t domain, SWIGTYPE_p_unsigned_int ndim) {
    return tiledbJNI.tiledb_domain_get_ndim(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain), SWIGTYPE_p_unsigned_int.getCPtr(ndim));
  }

  public static int tiledb_domain_add_dimension(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_domain_t domain, SWIGTYPE_p_tiledb_dimension_t dim) {
    return tiledbJNI.tiledb_domain_add_dimension(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain), SWIGTYPE_p_tiledb_dimension_t.getCPtr(dim));
  }

  public static int tiledb_domain_get_dimension_from_index(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_domain_t domain, long index, SWIGTYPE_p_p_tiledb_dimension_t dim) {
    return tiledbJNI.tiledb_domain_get_dimension_from_index(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain), index, SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(dim));
  }

  public static int tiledb_domain_get_dimension_from_name(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_domain_t domain, String name, SWIGTYPE_p_p_tiledb_dimension_t dim) {
    return tiledbJNI.tiledb_domain_get_dimension_from_name(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain), name, SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(dim));
  }

  public static int tiledb_domain_dump(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_domain_t domain, SWIGTYPE_p_FILE out) {
    return tiledbJNI.tiledb_domain_dump(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain), SWIGTYPE_p_FILE.getCPtr(out));
  }

  public static int tiledb_dimension_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, String name, tiledb_datatype_t type, SWIGTYPE_p_void dim_domain, SWIGTYPE_p_void tile_extent, SWIGTYPE_p_p_tiledb_dimension_t dim) {
    return tiledbJNI.tiledb_dimension_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), name, type.swigValue(), SWIGTYPE_p_void.getCPtr(dim_domain), SWIGTYPE_p_void.getCPtr(tile_extent), SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(dim));
  }

  public static void tiledb_dimension_free(SWIGTYPE_p_p_tiledb_dimension_t dim) {
    tiledbJNI.tiledb_dimension_free(SWIGTYPE_p_p_tiledb_dimension_t.getCPtr(dim));
  }

  public static int tiledb_dimension_get_name(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_dimension_t dim, SWIGTYPE_p_p_char name) {
    return tiledbJNI.tiledb_dimension_get_name(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_dimension_t.getCPtr(dim), SWIGTYPE_p_p_char.getCPtr(name));
  }

  public static int tiledb_dimension_get_type(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_dimension_t dim, SWIGTYPE_p_tiledb_datatype_t type) {
    return tiledbJNI.tiledb_dimension_get_type(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_dimension_t.getCPtr(dim), SWIGTYPE_p_tiledb_datatype_t.getCPtr(type));
  }

  public static int tiledb_dimension_get_domain(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_dimension_t dim, SWIGTYPE_p_p_void domain) {
    return tiledbJNI.tiledb_dimension_get_domain(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_dimension_t.getCPtr(dim), SWIGTYPE_p_p_void.getCPtr(domain));
  }

  public static int tiledb_dimension_get_tile_extent(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_dimension_t dim, SWIGTYPE_p_p_void tile_extent) {
    return tiledbJNI.tiledb_dimension_get_tile_extent(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_dimension_t.getCPtr(dim), SWIGTYPE_p_p_void.getCPtr(tile_extent));
  }

  public static int tiledb_dimension_dump(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_dimension_t dim, SWIGTYPE_p_FILE out) {
    return tiledbJNI.tiledb_dimension_dump(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_dimension_t.getCPtr(dim), SWIGTYPE_p_FILE.getCPtr(out));
  }

  public static int tiledb_array_schema_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, tiledb_array_type_t array_type, SWIGTYPE_p_p_tiledb_array_schema_t array_schema) {
    return tiledbJNI.tiledb_array_schema_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), array_type.swigValue(), SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(array_schema));
  }

  public static void tiledb_array_schema_free(SWIGTYPE_p_p_tiledb_array_schema_t array_schema) {
    tiledbJNI.tiledb_array_schema_free(SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(array_schema));
  }

  public static int tiledb_array_schema_add_attribute(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_tiledb_attribute_t attr) {
    return tiledbJNI.tiledb_array_schema_add_attribute(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static int tiledb_array_schema_set_domain(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_tiledb_domain_t domain) {
    return tiledbJNI.tiledb_array_schema_set_domain(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain));
  }

  public static int tiledb_array_schema_set_capacity(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, java.math.BigInteger capacity) {
    return tiledbJNI.tiledb_array_schema_set_capacity(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), capacity);
  }

  public static int tiledb_array_schema_set_cell_order(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, tiledb_layout_t cell_order) {
    return tiledbJNI.tiledb_array_schema_set_cell_order(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), cell_order.swigValue());
  }

  public static int tiledb_array_schema_set_tile_order(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, tiledb_layout_t tile_order) {
    return tiledbJNI.tiledb_array_schema_set_tile_order(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), tile_order.swigValue());
  }

  public static int tiledb_array_schema_set_coords_compressor(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, tiledb_compressor_t compressor, int compression_level) {
    return tiledbJNI.tiledb_array_schema_set_coords_compressor(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), compressor.swigValue(), compression_level);
  }

  public static int tiledb_array_schema_set_offsets_compressor(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, tiledb_compressor_t compressor, int compression_level) {
    return tiledbJNI.tiledb_array_schema_set_offsets_compressor(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), compressor.swigValue(), compression_level);
  }

  public static int tiledb_array_schema_check(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema) {
    return tiledbJNI.tiledb_array_schema_check(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema));
  }

  public static int tiledb_array_schema_load(SWIGTYPE_p_tiledb_ctx_t ctx, String array_uri, SWIGTYPE_p_p_tiledb_array_schema_t array_schema) {
    return tiledbJNI.tiledb_array_schema_load(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), array_uri, SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(array_schema));
  }

  public static int tiledb_array_schema_get_array_type(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_tiledb_array_type_t array_type) {
    return tiledbJNI.tiledb_array_schema_get_array_type(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_tiledb_array_type_t.getCPtr(array_type));
  }

  public static int tiledb_array_schema_get_capacity(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_unsigned_long_long capacity) {
    return tiledbJNI.tiledb_array_schema_get_capacity(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_unsigned_long_long.getCPtr(capacity));
  }

  public static int tiledb_array_schema_get_cell_order(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_tiledb_layout_t cell_order) {
    return tiledbJNI.tiledb_array_schema_get_cell_order(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_tiledb_layout_t.getCPtr(cell_order));
  }

  public static int tiledb_array_schema_get_coords_compressor(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_tiledb_compressor_t compressor, SWIGTYPE_p_int compression_level) {
    return tiledbJNI.tiledb_array_schema_get_coords_compressor(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_tiledb_compressor_t.getCPtr(compressor), SWIGTYPE_p_int.getCPtr(compression_level));
  }

  public static int tiledb_array_schema_get_offsets_compressor(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_tiledb_compressor_t compressor, SWIGTYPE_p_int compression_level) {
    return tiledbJNI.tiledb_array_schema_get_offsets_compressor(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_tiledb_compressor_t.getCPtr(compressor), SWIGTYPE_p_int.getCPtr(compression_level));
  }

  public static int tiledb_array_schema_get_domain(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_p_tiledb_domain_t domain) {
    return tiledbJNI.tiledb_array_schema_get_domain(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_p_tiledb_domain_t.getCPtr(domain));
  }

  public static int tiledb_array_schema_get_tile_order(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_tiledb_layout_t tile_order) {
    return tiledbJNI.tiledb_array_schema_get_tile_order(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_tiledb_layout_t.getCPtr(tile_order));
  }

  public static int tiledb_array_schema_get_attribute_num(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_unsigned_int attribute_num) {
    return tiledbJNI.tiledb_array_schema_get_attribute_num(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_unsigned_int.getCPtr(attribute_num));
  }

  public static int tiledb_array_schema_get_attribute_from_index(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, long index, SWIGTYPE_p_p_tiledb_attribute_t attr) {
    return tiledbJNI.tiledb_array_schema_get_attribute_from_index(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), index, SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static int tiledb_array_schema_get_attribute_from_name(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, String name, SWIGTYPE_p_p_tiledb_attribute_t attr) {
    return tiledbJNI.tiledb_array_schema_get_attribute_from_name(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), name, SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static int tiledb_array_schema_dump(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, SWIGTYPE_p_FILE out) {
    return tiledbJNI.tiledb_array_schema_dump(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), SWIGTYPE_p_FILE.getCPtr(out));
  }

  public static int tiledb_query_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array, tiledb_query_type_t query_type, SWIGTYPE_p_p_tiledb_query_t query) {
    return tiledbJNI.tiledb_query_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array), query_type.swigValue(), SWIGTYPE_p_p_tiledb_query_t.getCPtr(query));
  }

  public static int tiledb_query_set_subarray(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, SWIGTYPE_p_void subarray) {
    return tiledbJNI.tiledb_query_set_subarray(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), SWIGTYPE_p_void.getCPtr(subarray));
  }

  public static int tiledb_query_set_buffer(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, String attribute, SWIGTYPE_p_void buffer, SWIGTYPE_p_unsigned_long_long buffer_size) {
    return tiledbJNI.tiledb_query_set_buffer(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), attribute, SWIGTYPE_p_void.getCPtr(buffer), SWIGTYPE_p_unsigned_long_long.getCPtr(buffer_size));
  }

  public static int tiledb_query_set_buffer_var(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, String attribute, SWIGTYPE_p_unsigned_long_long buffer_off, SWIGTYPE_p_unsigned_long_long buffer_off_size, SWIGTYPE_p_void buffer_val, SWIGTYPE_p_unsigned_long_long buffer_val_size) {
    return tiledbJNI.tiledb_query_set_buffer_var(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), attribute, SWIGTYPE_p_unsigned_long_long.getCPtr(buffer_off), SWIGTYPE_p_unsigned_long_long.getCPtr(buffer_off_size), SWIGTYPE_p_void.getCPtr(buffer_val), SWIGTYPE_p_unsigned_long_long.getCPtr(buffer_val_size));
  }

  public static int tiledb_query_set_layout(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, tiledb_layout_t layout) {
    return tiledbJNI.tiledb_query_set_layout(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), layout.swigValue());
  }

  public static int tiledb_query_finalize(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query) {
    return tiledbJNI.tiledb_query_finalize(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query));
  }

  public static void tiledb_query_free(SWIGTYPE_p_p_tiledb_query_t query) {
    tiledbJNI.tiledb_query_free(SWIGTYPE_p_p_tiledb_query_t.getCPtr(query));
  }

  public static int tiledb_query_submit(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query) {
    return tiledbJNI.tiledb_query_submit(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query));
  }

  public static int tiledb_query_submit_async(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, SWIGTYPE_p_f_p_void__void callback, SWIGTYPE_p_void callback_data) {
    return tiledbJNI.tiledb_query_submit_async(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), SWIGTYPE_p_f_p_void__void.getCPtr(callback), SWIGTYPE_p_void.getCPtr(callback_data));
  }

  public static int tiledb_query_has_results(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, SWIGTYPE_p_int has_results) {
    return tiledbJNI.tiledb_query_has_results(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), SWIGTYPE_p_int.getCPtr(has_results));
  }

  public static int tiledb_query_get_status(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, SWIGTYPE_p_tiledb_query_status_t status) {
    return tiledbJNI.tiledb_query_get_status(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), SWIGTYPE_p_tiledb_query_status_t.getCPtr(status));
  }

  public static int tiledb_query_get_type(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, SWIGTYPE_p_tiledb_query_type_t query_type) {
    return tiledbJNI.tiledb_query_get_type(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), SWIGTYPE_p_tiledb_query_type_t.getCPtr(query_type));
  }

  public static int tiledb_array_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, String array_uri, SWIGTYPE_p_p_tiledb_array_t array) {
    return tiledbJNI.tiledb_array_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), array_uri, SWIGTYPE_p_p_tiledb_array_t.getCPtr(array));
  }

  public static int tiledb_array_open(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array, tiledb_query_type_t query_type) {
    return tiledbJNI.tiledb_array_open(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array), query_type.swigValue());
  }

  public static int tiledb_array_is_open(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array, SWIGTYPE_p_int is_open) {
    return tiledbJNI.tiledb_array_is_open(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array), SWIGTYPE_p_int.getCPtr(is_open));
  }

  public static int tiledb_array_reopen(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array) {
    return tiledbJNI.tiledb_array_reopen(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array));
  }

  public static int tiledb_array_close(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array) {
    return tiledbJNI.tiledb_array_close(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array));
  }

  public static void tiledb_array_free(SWIGTYPE_p_p_tiledb_array_t array) {
    tiledbJNI.tiledb_array_free(SWIGTYPE_p_p_tiledb_array_t.getCPtr(array));
  }

  public static int tiledb_array_get_schema(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array, SWIGTYPE_p_p_tiledb_array_schema_t array_schema) {
    return tiledbJNI.tiledb_array_get_schema(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array), SWIGTYPE_p_p_tiledb_array_schema_t.getCPtr(array_schema));
  }

  public static int tiledb_array_get_query_type(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array, SWIGTYPE_p_tiledb_query_type_t query_type) {
    return tiledbJNI.tiledb_array_get_query_type(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array), SWIGTYPE_p_tiledb_query_type_t.getCPtr(query_type));
  }

  public static int tiledb_array_create(SWIGTYPE_p_tiledb_ctx_t ctx, String array_uri, SWIGTYPE_p_tiledb_array_schema_t array_schema) {
    return tiledbJNI.tiledb_array_create(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), array_uri, SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema));
  }

  public static int tiledb_array_consolidate(SWIGTYPE_p_tiledb_ctx_t ctx, String array_uri) {
    return tiledbJNI.tiledb_array_consolidate(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), array_uri);
  }

  public static int tiledb_array_get_non_empty_domain(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array, SWIGTYPE_p_void domain, SWIGTYPE_p_int is_empty) {
    return tiledbJNI.tiledb_array_get_non_empty_domain(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array), SWIGTYPE_p_void.getCPtr(domain), SWIGTYPE_p_int.getCPtr(is_empty));
  }

  public static int tiledb_array_max_buffer_size(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array, String attribute, SWIGTYPE_p_void subarray, SWIGTYPE_p_unsigned_long_long buffer_size) {
    return tiledbJNI.tiledb_array_max_buffer_size(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array), attribute, SWIGTYPE_p_void.getCPtr(subarray), SWIGTYPE_p_unsigned_long_long.getCPtr(buffer_size));
  }

  public static int tiledb_array_max_buffer_size_var(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_t array, String attribute, SWIGTYPE_p_void subarray, SWIGTYPE_p_unsigned_long_long buffer_off_size, SWIGTYPE_p_unsigned_long_long buffer_val_size) {
    return tiledbJNI.tiledb_array_max_buffer_size_var(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_t.getCPtr(array), attribute, SWIGTYPE_p_void.getCPtr(subarray), SWIGTYPE_p_unsigned_long_long.getCPtr(buffer_off_size), SWIGTYPE_p_unsigned_long_long.getCPtr(buffer_val_size));
  }

  public static int tiledb_object_type(SWIGTYPE_p_tiledb_ctx_t ctx, String path, SWIGTYPE_p_tiledb_object_t type) {
    return tiledbJNI.tiledb_object_type(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), path, SWIGTYPE_p_tiledb_object_t.getCPtr(type));
  }

  public static int tiledb_object_remove(SWIGTYPE_p_tiledb_ctx_t ctx, String path) {
    return tiledbJNI.tiledb_object_remove(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), path);
  }

  public static int tiledb_object_move(SWIGTYPE_p_tiledb_ctx_t ctx, String old_path, String new_path) {
    return tiledbJNI.tiledb_object_move(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), old_path, new_path);
  }

  public static int tiledb_object_walk(SWIGTYPE_p_tiledb_ctx_t ctx, String path, tiledb_walk_order_t order, SWIGTYPE_p_f_p_q_const__char_enum_tiledb_object_t_p_void__int callback, SWIGTYPE_p_void data) {
    return tiledbJNI.tiledb_object_walk(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), path, order.swigValue(), SWIGTYPE_p_f_p_q_const__char_enum_tiledb_object_t_p_void__int.getCPtr(callback), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int tiledb_object_ls(SWIGTYPE_p_tiledb_ctx_t ctx, String path, SWIGTYPE_p_f_p_q_const__char_enum_tiledb_object_t_p_void__int callback, SWIGTYPE_p_void data) {
    return tiledbJNI.tiledb_object_ls(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), path, SWIGTYPE_p_f_p_q_const__char_enum_tiledb_object_t_p_void__int.getCPtr(callback), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int tiledb_kv_schema_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_p_tiledb_kv_schema_t kv_schema) {
    return tiledbJNI.tiledb_kv_schema_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(kv_schema));
  }

  public static void tiledb_kv_schema_free(SWIGTYPE_p_p_tiledb_kv_schema_t kv_schema) {
    tiledbJNI.tiledb_kv_schema_free(SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(kv_schema));
  }

  public static int tiledb_kv_schema_add_attribute(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema, SWIGTYPE_p_tiledb_attribute_t attr) {
    return tiledbJNI.tiledb_kv_schema_add_attribute(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static int tiledb_kv_schema_set_capacity(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema, java.math.BigInteger capacity) {
    return tiledbJNI.tiledb_kv_schema_set_capacity(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema), capacity);
  }

  public static int tiledb_kv_schema_check(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema) {
    return tiledbJNI.tiledb_kv_schema_check(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema));
  }

  public static int tiledb_kv_schema_load(SWIGTYPE_p_tiledb_ctx_t ctx, String kv_uri, SWIGTYPE_p_p_tiledb_kv_schema_t kv_schema) {
    return tiledbJNI.tiledb_kv_schema_load(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), kv_uri, SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(kv_schema));
  }

  public static int tiledb_kv_schema_get_capacity(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema, SWIGTYPE_p_unsigned_long_long capacity) {
    return tiledbJNI.tiledb_kv_schema_get_capacity(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema), SWIGTYPE_p_unsigned_long_long.getCPtr(capacity));
  }

  public static int tiledb_kv_schema_get_attribute_num(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema, SWIGTYPE_p_unsigned_int attribute_num) {
    return tiledbJNI.tiledb_kv_schema_get_attribute_num(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema), SWIGTYPE_p_unsigned_int.getCPtr(attribute_num));
  }

  public static int tiledb_kv_schema_get_attribute_from_index(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema, long index, SWIGTYPE_p_p_tiledb_attribute_t attr) {
    return tiledbJNI.tiledb_kv_schema_get_attribute_from_index(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema), index, SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static int tiledb_kv_schema_get_attribute_from_name(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema, String name, SWIGTYPE_p_p_tiledb_attribute_t attr) {
    return tiledbJNI.tiledb_kv_schema_get_attribute_from_name(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema), name, SWIGTYPE_p_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static int tiledb_kv_schema_dump(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema, SWIGTYPE_p_FILE out) {
    return tiledbJNI.tiledb_kv_schema_dump(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema), SWIGTYPE_p_FILE.getCPtr(out));
  }

  public static int tiledb_kv_item_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_p_tiledb_kv_item_t kv_item) {
    return tiledbJNI.tiledb_kv_item_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(kv_item));
  }

  public static void tiledb_kv_item_free(SWIGTYPE_p_p_tiledb_kv_item_t kv_item) {
    tiledbJNI.tiledb_kv_item_free(SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(kv_item));
  }

  public static int tiledb_kv_item_set_key(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_item_t kv_item, SWIGTYPE_p_void key, tiledb_datatype_t key_type, java.math.BigInteger key_size) {
    return tiledbJNI.tiledb_kv_item_set_key(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_item_t.getCPtr(kv_item), SWIGTYPE_p_void.getCPtr(key), key_type.swigValue(), key_size);
  }

  public static int tiledb_kv_item_set_value(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_item_t kv_item, String attribute, SWIGTYPE_p_void value, tiledb_datatype_t value_type, java.math.BigInteger value_size) {
    return tiledbJNI.tiledb_kv_item_set_value(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_item_t.getCPtr(kv_item), attribute, SWIGTYPE_p_void.getCPtr(value), value_type.swigValue(), value_size);
  }

  public static int tiledb_kv_item_get_key(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_item_t kv_item, SWIGTYPE_p_p_void key, SWIGTYPE_p_tiledb_datatype_t key_type, SWIGTYPE_p_unsigned_long_long key_size) {
    return tiledbJNI.tiledb_kv_item_get_key(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_item_t.getCPtr(kv_item), SWIGTYPE_p_p_void.getCPtr(key), SWIGTYPE_p_tiledb_datatype_t.getCPtr(key_type), SWIGTYPE_p_unsigned_long_long.getCPtr(key_size));
  }

  public static int tiledb_kv_item_get_value(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_item_t kv_item, String attribute, SWIGTYPE_p_p_void value, SWIGTYPE_p_tiledb_datatype_t value_type, SWIGTYPE_p_unsigned_long_long value_size) {
    return tiledbJNI.tiledb_kv_item_get_value(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_item_t.getCPtr(kv_item), attribute, SWIGTYPE_p_p_void.getCPtr(value), SWIGTYPE_p_tiledb_datatype_t.getCPtr(value_type), SWIGTYPE_p_unsigned_long_long.getCPtr(value_size));
  }

  public static int tiledb_kv_create(SWIGTYPE_p_tiledb_ctx_t ctx, String kv_uri, SWIGTYPE_p_tiledb_kv_schema_t kv_schema) {
    return tiledbJNI.tiledb_kv_create(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), kv_uri, SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema));
  }

  public static int tiledb_kv_consolidate(SWIGTYPE_p_tiledb_ctx_t ctx, String kv_uri) {
    return tiledbJNI.tiledb_kv_consolidate(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), kv_uri);
  }

  public static int tiledb_kv_set_max_buffered_items(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv, java.math.BigInteger max_items) {
    return tiledbJNI.tiledb_kv_set_max_buffered_items(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv), max_items);
  }

  public static int tiledb_kv_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, String kv_uri, SWIGTYPE_p_p_tiledb_kv_t kv) {
    return tiledbJNI.tiledb_kv_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), kv_uri, SWIGTYPE_p_p_tiledb_kv_t.getCPtr(kv));
  }

  public static int tiledb_kv_open(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv, SWIGTYPE_p_p_char attributes, long attribute_num) {
    return tiledbJNI.tiledb_kv_open(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv), SWIGTYPE_p_p_char.getCPtr(attributes), attribute_num);
  }

  public static int tiledb_kv_reopen(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv) {
    return tiledbJNI.tiledb_kv_reopen(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv));
  }

  public static int tiledb_kv_close(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv) {
    return tiledbJNI.tiledb_kv_close(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv));
  }

  public static void tiledb_kv_free(SWIGTYPE_p_p_tiledb_kv_t kv) {
    tiledbJNI.tiledb_kv_free(SWIGTYPE_p_p_tiledb_kv_t.getCPtr(kv));
  }

  public static int tiledb_kv_get_schema(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv, SWIGTYPE_p_p_tiledb_kv_schema_t kv_schema) {
    return tiledbJNI.tiledb_kv_get_schema(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv), SWIGTYPE_p_p_tiledb_kv_schema_t.getCPtr(kv_schema));
  }

  public static int tiledb_kv_is_dirty(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv, SWIGTYPE_p_int is_dirty) {
    return tiledbJNI.tiledb_kv_is_dirty(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv), SWIGTYPE_p_int.getCPtr(is_dirty));
  }

  public static int tiledb_kv_add_item(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv, SWIGTYPE_p_tiledb_kv_item_t kv_item) {
    return tiledbJNI.tiledb_kv_add_item(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv), SWIGTYPE_p_tiledb_kv_item_t.getCPtr(kv_item));
  }

  public static int tiledb_kv_flush(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv) {
    return tiledbJNI.tiledb_kv_flush(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv));
  }

  public static int tiledb_kv_get_item(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv, SWIGTYPE_p_void key, tiledb_datatype_t key_type, java.math.BigInteger key_size, SWIGTYPE_p_p_tiledb_kv_item_t kv_item) {
    return tiledbJNI.tiledb_kv_get_item(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv), SWIGTYPE_p_void.getCPtr(key), key_type.swigValue(), key_size, SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(kv_item));
  }

  public static int tiledb_kv_has_key(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv, SWIGTYPE_p_void key, tiledb_datatype_t key_type, java.math.BigInteger key_size, SWIGTYPE_p_int has_key) {
    return tiledbJNI.tiledb_kv_has_key(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv), SWIGTYPE_p_void.getCPtr(key), key_type.swigValue(), key_size, SWIGTYPE_p_int.getCPtr(has_key));
  }

  public static int tiledb_kv_iter_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_t kv, SWIGTYPE_p_p_tiledb_kv_iter_t kv_iter) {
    return tiledbJNI.tiledb_kv_iter_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_t.getCPtr(kv), SWIGTYPE_p_p_tiledb_kv_iter_t.getCPtr(kv_iter));
  }

  public static void tiledb_kv_iter_free(SWIGTYPE_p_p_tiledb_kv_iter_t kv_iter) {
    tiledbJNI.tiledb_kv_iter_free(SWIGTYPE_p_p_tiledb_kv_iter_t.getCPtr(kv_iter));
  }

  public static int tiledb_kv_iter_here(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_iter_t kv_iter, SWIGTYPE_p_p_tiledb_kv_item_t kv_item) {
    return tiledbJNI.tiledb_kv_iter_here(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(kv_iter), SWIGTYPE_p_p_tiledb_kv_item_t.getCPtr(kv_item));
  }

  public static int tiledb_kv_iter_next(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_iter_t kv_iter) {
    return tiledbJNI.tiledb_kv_iter_next(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(kv_iter));
  }

  public static int tiledb_kv_iter_done(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_iter_t kv_iter, SWIGTYPE_p_int done) {
    return tiledbJNI.tiledb_kv_iter_done(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(kv_iter), SWIGTYPE_p_int.getCPtr(done));
  }

  public static int tiledb_kv_iter_reset(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_iter_t kv_iter) {
    return tiledbJNI.tiledb_kv_iter_reset(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_iter_t.getCPtr(kv_iter));
  }

  public static int tiledb_vfs_alloc(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_config_t config, SWIGTYPE_p_p_tiledb_vfs_t vfs) {
    return tiledbJNI.tiledb_vfs_alloc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_config_t.getCPtr(config), SWIGTYPE_p_p_tiledb_vfs_t.getCPtr(vfs));
  }

  public static void tiledb_vfs_free(SWIGTYPE_p_p_tiledb_vfs_t vfs) {
    tiledbJNI.tiledb_vfs_free(SWIGTYPE_p_p_tiledb_vfs_t.getCPtr(vfs));
  }

  public static int tiledb_vfs_get_config(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, SWIGTYPE_p_p_tiledb_config_t config) {
    return tiledbJNI.tiledb_vfs_get_config(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), SWIGTYPE_p_p_tiledb_config_t.getCPtr(config));
  }

  public static int tiledb_vfs_create_bucket(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri) {
    return tiledbJNI.tiledb_vfs_create_bucket(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri);
  }

  public static int tiledb_vfs_remove_bucket(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri) {
    return tiledbJNI.tiledb_vfs_remove_bucket(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri);
  }

  public static int tiledb_vfs_empty_bucket(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri) {
    return tiledbJNI.tiledb_vfs_empty_bucket(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri);
  }

  public static int tiledb_vfs_is_empty_bucket(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri, SWIGTYPE_p_int is_empty) {
    return tiledbJNI.tiledb_vfs_is_empty_bucket(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri, SWIGTYPE_p_int.getCPtr(is_empty));
  }

  public static int tiledb_vfs_is_bucket(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri, SWIGTYPE_p_int is_bucket) {
    return tiledbJNI.tiledb_vfs_is_bucket(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri, SWIGTYPE_p_int.getCPtr(is_bucket));
  }

  public static int tiledb_vfs_create_dir(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri) {
    return tiledbJNI.tiledb_vfs_create_dir(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri);
  }

  public static int tiledb_vfs_is_dir(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri, SWIGTYPE_p_int is_dir) {
    return tiledbJNI.tiledb_vfs_is_dir(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri, SWIGTYPE_p_int.getCPtr(is_dir));
  }

  public static int tiledb_vfs_remove_dir(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri) {
    return tiledbJNI.tiledb_vfs_remove_dir(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri);
  }

  public static int tiledb_vfs_is_file(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri, SWIGTYPE_p_int is_file) {
    return tiledbJNI.tiledb_vfs_is_file(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri, SWIGTYPE_p_int.getCPtr(is_file));
  }

  public static int tiledb_vfs_remove_file(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri) {
    return tiledbJNI.tiledb_vfs_remove_file(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri);
  }

  public static int tiledb_vfs_file_size(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri, SWIGTYPE_p_unsigned_long_long size) {
    return tiledbJNI.tiledb_vfs_file_size(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri, SWIGTYPE_p_unsigned_long_long.getCPtr(size));
  }

  public static int tiledb_vfs_move_file(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String old_uri, String new_uri) {
    return tiledbJNI.tiledb_vfs_move_file(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), old_uri, new_uri);
  }

  public static int tiledb_vfs_move_dir(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String old_uri, String new_uri) {
    return tiledbJNI.tiledb_vfs_move_dir(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), old_uri, new_uri);
  }

  public static int tiledb_vfs_open(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri, tiledb_vfs_mode_t mode, SWIGTYPE_p_p_tiledb_vfs_fh_t fh) {
    return tiledbJNI.tiledb_vfs_open(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri, mode.swigValue(), SWIGTYPE_p_p_tiledb_vfs_fh_t.getCPtr(fh));
  }

  public static int tiledb_vfs_close(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_fh_t fh) {
    return tiledbJNI.tiledb_vfs_close(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(fh));
  }

  public static int tiledb_vfs_read(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_fh_t fh, java.math.BigInteger offset, SWIGTYPE_p_void buffer, java.math.BigInteger nbytes) {
    return tiledbJNI.tiledb_vfs_read(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(fh), offset, SWIGTYPE_p_void.getCPtr(buffer), nbytes);
  }

  public static int tiledb_vfs_write(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_fh_t fh, SWIGTYPE_p_void buffer, java.math.BigInteger nbytes) {
    return tiledbJNI.tiledb_vfs_write(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(fh), SWIGTYPE_p_void.getCPtr(buffer), nbytes);
  }

  public static int tiledb_vfs_sync(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_fh_t fh) {
    return tiledbJNI.tiledb_vfs_sync(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(fh));
  }

  public static void tiledb_vfs_fh_free(SWIGTYPE_p_p_tiledb_vfs_fh_t fh) {
    tiledbJNI.tiledb_vfs_fh_free(SWIGTYPE_p_p_tiledb_vfs_fh_t.getCPtr(fh));
  }

  public static int tiledb_vfs_fh_is_closed(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_fh_t fh, SWIGTYPE_p_int is_closed) {
    return tiledbJNI.tiledb_vfs_fh_is_closed(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_fh_t.getCPtr(fh), SWIGTYPE_p_int.getCPtr(is_closed));
  }

  public static int tiledb_vfs_touch(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_vfs_t vfs, String uri) {
    return tiledbJNI.tiledb_vfs_touch(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_vfs_t.getCPtr(vfs), uri);
  }

  public static int tiledb_uri_to_path(SWIGTYPE_p_tiledb_ctx_t ctx, String uri, String path_out, SWIGTYPE_p_unsigned_int path_length) {
    return tiledbJNI.tiledb_uri_to_path(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), uri, path_out, SWIGTYPE_p_unsigned_int.getCPtr(path_length));
  }

  public static int tiledb_stats_enable() {
    return tiledbJNI.tiledb_stats_enable();
  }

  public static int tiledb_stats_disable() {
    return tiledbJNI.tiledb_stats_disable();
  }

  public static int tiledb_stats_reset() {
    return tiledbJNI.tiledb_stats_reset();
  }

  public static int tiledb_stats_dump(SWIGTYPE_p_FILE out) {
    return tiledbJNI.tiledb_stats_dump(SWIGTYPE_p_FILE.getCPtr(out));
  }

  public static int tiledb_dimension_dump_stdout(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_dimension_t dim) {
    return tiledbJNI.tiledb_dimension_dump_stdout(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_dimension_t.getCPtr(dim));
  }

  public static int tiledb_kv_schema_dump_stdout(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema) {
    return tiledbJNI.tiledb_kv_schema_dump_stdout(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema));
  }

  public static int tiledb_attribute_dump_stdout(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr) {
    return tiledbJNI.tiledb_attribute_dump_stdout(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr));
  }

  public static int tiledb_domain_dump_stdout(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_domain_t domain) {
    return tiledbJNI.tiledb_domain_dump_stdout(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain));
  }

  public static int tiledb_array_schema_dump_stdout(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema) {
    return tiledbJNI.tiledb_array_schema_dump_stdout(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema));
  }

  public static int tiledb_stats_dump_stdout() {
    return tiledbJNI.tiledb_stats_dump_stdout();
  }

  public static int tiledb_dimension_dump_file(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_dimension_t dim, String filename) {
    return tiledbJNI.tiledb_dimension_dump_file(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_dimension_t.getCPtr(dim), filename);
  }

  public static int tiledb_kv_schema_dump_file(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_kv_schema_t kv_schema, String filename) {
    return tiledbJNI.tiledb_kv_schema_dump_file(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_kv_schema_t.getCPtr(kv_schema), filename);
  }

  public static int tiledb_attribute_dump_file(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_attribute_t attr, String filename) {
    return tiledbJNI.tiledb_attribute_dump_file(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_attribute_t.getCPtr(attr), filename);
  }

  public static int tiledb_domain_dump_file(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_domain_t domain, String filename) {
    return tiledbJNI.tiledb_domain_dump_file(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_domain_t.getCPtr(domain), filename);
  }

  public static int tiledb_array_schema_dump_file(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_array_schema_t array_schema, String filename) {
    return tiledbJNI.tiledb_array_schema_dump_file(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_array_schema_t.getCPtr(array_schema), filename);
  }

  public static int tiledb_stats_dump_file(String filename) {
    return tiledbJNI.tiledb_stats_dump_file(filename);
  }

  public static SWIGTYPE_p_void derefVoid(SWIGTYPE_p_p_void in) {
    long cPtr = tiledbJNI.derefVoid(SWIGTYPE_p_p_void.getCPtr(in));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void print_upon_completion(SWIGTYPE_p_void s) {
    tiledbJNI.print_upon_completion(SWIGTYPE_p_void.getCPtr(s));
  }

  public static int print_path(String path, tiledb_object_t type, SWIGTYPE_p_void data) {
    return tiledbJNI.print_path(path, type.swigValue(), SWIGTYPE_p_void.getCPtr(data));
  }

  public static SWIGTYPE_p_f_p_void__void native_callback() {
    long cPtr = tiledbJNI.native_callback();
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public static SWIGTYPE_p_f_p_q_const__char_enum_tiledb_object_t_p_void__int native_walk_callback() {
    long cPtr = tiledbJNI.native_walk_callback();
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_enum_tiledb_object_t_p_void__int(cPtr, false);
  }

  public static int tiledb_query_submit_async_jc(SWIGTYPE_p_tiledb_ctx_t ctx, SWIGTYPE_p_tiledb_query_t query, SWIGTYPE_p_f_p_void__void callback, Object callback_data) {
    return tiledbJNI.tiledb_query_submit_async_jc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), SWIGTYPE_p_tiledb_query_t.getCPtr(query), SWIGTYPE_p_f_p_void__void.getCPtr(callback), callback_data);
  }

  public static int tiledb_object_walk_jc(SWIGTYPE_p_tiledb_ctx_t ctx, String path, tiledb_walk_order_t order, SWIGTYPE_p_f_p_q_const__char_enum_tiledb_object_t_p_void__int callback, SWIGTYPE_p_void callback_data) {
    return tiledbJNI.tiledb_object_walk_jc(SWIGTYPE_p_tiledb_ctx_t.getCPtr(ctx), path, order.swigValue(), SWIGTYPE_p_f_p_q_const__char_enum_tiledb_object_t_p_void__int.getCPtr(callback), SWIGTYPE_p_void.getCPtr(callback_data));
  }


  
  public static int sizeOfType(Object array) {
    Class arrayClass = array.getClass();
    if (arrayClass.equals(int32_tArray.class)) {
      return sizeOfInt32();
    } else if (arrayClass.equals(int64_tArray.class)) {
      return sizeOfInt64();
    } else if (arrayClass.equals(charArray.class)) {
      return sizeOfChar();
    } else if (arrayClass.equals(floatArray.class)) {
      return sizeOfFloat();
    } else if (arrayClass.equals(doubleArray.class)) {
      return sizeOfDouble();
    } else if (arrayClass.equals(int8_tArray.class)) {
      return sizeOfInt8();
    } else if (arrayClass.equals(uint8_tArray.class)) {
      return sizeOfUint8();
    } else if (arrayClass.equals(int16_tArray.class)) {
      return sizeOfInt16();
    } else if (arrayClass.equals(uint16_tArray.class)) {
      return sizeOfUint16();
    } else if (arrayClass.equals(uint32_tArray.class)) {
      return sizeOfUint32();
    } else if (arrayClass.equals(uint64_tArray.class)) {
      return sizeOfUint64();
    }
    return -1;
  }

}
