/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public interface tiledbConstants {
  public static final int TILEDB_COMPRESSION_FILTER_DEFAULT_LEVEL = (-30000);
  public static final int TILEDB_ERR = (-1);
  public static final int TILEDB_INVALID_CONTEXT = (-3);
  public static final int TILEDB_INVALID_ERROR = (-4);
  public static final int TILEDB_OK = (0);
  public static final int TILEDB_OOM = (-2);
  public static final int TILEDB_VERSION_MAJOR = 2;
  public static final int TILEDB_VERSION_MINOR = 18;
  public static final int TILEDB_VERSION_PATCH = 0;
}
