/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 TileDB, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public class tiledbUtilsJNI {
  public final static native long new_intp();

  public final static native long copy_intp(int jarg1);

  public final static native void delete_intp(long jarg1);

  public final static native void intp_assign(long jarg1, int jarg2);

  public final static native int intp_value(long jarg1);

  public final static native long new_floatp();

  public final static native long copy_floatp(float jarg1);

  public final static native void delete_floatp(long jarg1);

  public final static native void floatp_assign(long jarg1, float jarg2);

  public final static native float floatp_value(long jarg1);

  public final static native long new_intpp();

  public final static native long copy_intpp(long jarg1);

  public final static native void delete_intpp(long jarg1);

  public final static native void intpp_assign(long jarg1, long jarg2);

  public final static native long intpp_value(long jarg1);

  public final static native long new_charpp();

  public final static native long copy_charpp(String jarg1);

  public final static native void delete_charpp(long jarg1);

  public final static native void charpp_assign(long jarg1, String jarg2);

  public final static native String charpp_value(long jarg1);

  public final static native long new_uintp();

  public final static native long copy_uintp(long jarg1);

  public final static native void delete_uintp(long jarg1);

  public final static native void uintp_assign(long jarg1, long jarg2);

  public final static native long uintp_value(long jarg1);

  public final static native long new_ullp();

  public final static native long copy_ullp(java.math.BigInteger jarg1);

  public final static native void delete_ullp(long jarg1);

  public final static native void ullp_assign(long jarg1, java.math.BigInteger jarg2);

  public final static native java.math.BigInteger ullp_value(long jarg1);

  public final static native long new_tiledb_config_tp();

  public final static native long copy_tiledb_config_tp(long jarg1);

  public final static native void delete_tiledb_config_tp(long jarg1);

  public final static native void tiledb_config_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_config_tp_value(long jarg1);

  public final static native long new_tiledb_config_tpp();

  public final static native long copy_tiledb_config_tpp(long jarg1);

  public final static native void delete_tiledb_config_tpp(long jarg1);

  public final static native void tiledb_config_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_config_tpp_value(long jarg1);

  public final static native long new_tiledb_config_iter_tp();

  public final static native long copy_tiledb_config_iter_tp(long jarg1);

  public final static native void delete_tiledb_config_iter_tp(long jarg1);

  public final static native void tiledb_config_iter_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_config_iter_tp_value(long jarg1);

  public final static native long new_tiledb_config_iter_tpp();

  public final static native long copy_tiledb_config_iter_tpp(long jarg1);

  public final static native void delete_tiledb_config_iter_tpp(long jarg1);

  public final static native void tiledb_config_iter_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_config_iter_tpp_value(long jarg1);

  public final static native long new_tiledb_ctx_tp();

  public final static native long copy_tiledb_ctx_tp(long jarg1);

  public final static native void delete_tiledb_ctx_tp(long jarg1);

  public final static native void tiledb_ctx_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_ctx_tp_value(long jarg1);

  public final static native long new_tiledb_ctx_tpp();

  public final static native long copy_tiledb_ctx_tpp(long jarg1);

  public final static native void delete_tiledb_ctx_tpp(long jarg1);

  public final static native void tiledb_ctx_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_ctx_tpp_value(long jarg1);

  public final static native long new_tiledb_error_tp();

  public final static native long copy_tiledb_error_tp(long jarg1);

  public final static native void delete_tiledb_error_tp(long jarg1);

  public final static native void tiledb_error_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_error_tp_value(long jarg1);

  public final static native long new_tiledb_error_tpp();

  public final static native long copy_tiledb_error_tpp(long jarg1);

  public final static native void delete_tiledb_error_tpp(long jarg1);

  public final static native void tiledb_error_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_error_tpp_value(long jarg1);

  public final static native long new_tiledb_attribute_tp();

  public final static native long copy_tiledb_attribute_tp(long jarg1);

  public final static native void delete_tiledb_attribute_tp(long jarg1);

  public final static native void tiledb_attribute_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_attribute_tp_value(long jarg1);

  public final static native long new_tiledb_attribute_tpp();

  public final static native long copy_tiledb_attribute_tpp(long jarg1);

  public final static native void delete_tiledb_attribute_tpp(long jarg1);

  public final static native void tiledb_attribute_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_attribute_tpp_value(long jarg1);

  public final static native long new_tiledb_array_schema_tp();

  public final static native long copy_tiledb_array_schema_tp(long jarg1);

  public final static native void delete_tiledb_array_schema_tp(long jarg1);

  public final static native void tiledb_array_schema_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_array_schema_tp_value(long jarg1);

  public final static native long new_tiledb_array_schema_tpp();

  public final static native long copy_tiledb_array_schema_tpp(long jarg1);

  public final static native void delete_tiledb_array_schema_tpp(long jarg1);

  public final static native void tiledb_array_schema_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_array_schema_tpp_value(long jarg1);

  public final static native long new_tiledb_dimension_tp();

  public final static native long copy_tiledb_dimension_tp(long jarg1);

  public final static native void delete_tiledb_dimension_tp(long jarg1);

  public final static native void tiledb_dimension_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_dimension_tp_value(long jarg1);

  public final static native long new_tiledb_dimension_tpp();

  public final static native long copy_tiledb_dimension_tpp(long jarg1);

  public final static native void delete_tiledb_dimension_tpp(long jarg1);

  public final static native void tiledb_dimension_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_dimension_tpp_value(long jarg1);

  public final static native long new_tiledb_domain_tp();

  public final static native long copy_tiledb_domain_tp(long jarg1);

  public final static native void delete_tiledb_domain_tp(long jarg1);

  public final static native void tiledb_domain_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_domain_tp_value(long jarg1);

  public final static native long new_tiledb_domain_tpp();

  public final static native long copy_tiledb_domain_tpp(long jarg1);

  public final static native void delete_tiledb_domain_tpp(long jarg1);

  public final static native void tiledb_domain_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_domain_tpp_value(long jarg1);

  public final static native long new_tiledb_query_tp();

  public final static native long copy_tiledb_query_tp(long jarg1);

  public final static native void delete_tiledb_query_tp(long jarg1);

  public final static native void tiledb_query_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_query_tp_value(long jarg1);

  public final static native long new_tiledb_query_tpp();

  public final static native long copy_tiledb_query_tpp(long jarg1);

  public final static native void delete_tiledb_query_tpp(long jarg1);

  public final static native void tiledb_query_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_query_tpp_value(long jarg1);

  public final static native long new_tiledb_kv_schema_tp();

  public final static native long copy_tiledb_kv_schema_tp(long jarg1);

  public final static native void delete_tiledb_kv_schema_tp(long jarg1);

  public final static native void tiledb_kv_schema_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_kv_schema_tp_value(long jarg1);

  public final static native long new_tiledb_kv_schema_tpp();

  public final static native long copy_tiledb_kv_schema_tpp(long jarg1);

  public final static native void delete_tiledb_kv_schema_tpp(long jarg1);

  public final static native void tiledb_kv_schema_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_kv_schema_tpp_value(long jarg1);

  public final static native long new_tiledb_kv_tp();

  public final static native long copy_tiledb_kv_tp(long jarg1);

  public final static native void delete_tiledb_kv_tp(long jarg1);

  public final static native void tiledb_kv_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_kv_tp_value(long jarg1);

  public final static native long new_tiledb_kv_tpp();

  public final static native long copy_tiledb_kv_tpp(long jarg1);

  public final static native void delete_tiledb_kv_tpp(long jarg1);

  public final static native void tiledb_kv_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_kv_tpp_value(long jarg1);

  public final static native long new_tiledb_kv_item_tp();

  public final static native long copy_tiledb_kv_item_tp(long jarg1);

  public final static native void delete_tiledb_kv_item_tp(long jarg1);

  public final static native void tiledb_kv_item_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_kv_item_tp_value(long jarg1);

  public final static native long new_tiledb_kv_item_tpp();

  public final static native long copy_tiledb_kv_item_tpp(long jarg1);

  public final static native void delete_tiledb_kv_item_tpp(long jarg1);

  public final static native void tiledb_kv_item_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_kv_item_tpp_value(long jarg1);

  public final static native long new_tiledb_kv_iter_tp();

  public final static native long copy_tiledb_kv_iter_tp(long jarg1);

  public final static native void delete_tiledb_kv_iter_tp(long jarg1);

  public final static native void tiledb_kv_iter_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_kv_iter_tp_value(long jarg1);

  public final static native long new_tiledb_kv_iter_tpp();

  public final static native long copy_tiledb_kv_iter_tpp(long jarg1);

  public final static native void delete_tiledb_kv_iter_tpp(long jarg1);

  public final static native void tiledb_kv_iter_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_kv_iter_tpp_value(long jarg1);

  public final static native long new_tiledb_vfs_tp();

  public final static native long copy_tiledb_vfs_tp(long jarg1);

  public final static native void delete_tiledb_vfs_tp(long jarg1);

  public final static native void tiledb_vfs_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_vfs_tp_value(long jarg1);

  public final static native long new_tiledb_vfs_tpp();

  public final static native long copy_tiledb_vfs_tpp(long jarg1);

  public final static native void delete_tiledb_vfs_tpp(long jarg1);

  public final static native void tiledb_vfs_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_vfs_tpp_value(long jarg1);

  public final static native long new_tiledb_vfs_fh_tp();

  public final static native long copy_tiledb_vfs_fh_tp(long jarg1);

  public final static native void delete_tiledb_vfs_fh_tp(long jarg1);

  public final static native void tiledb_vfs_fh_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_vfs_fh_tp_value(long jarg1);

  public final static native long new_tiledb_vfs_fh_tpp();

  public final static native long copy_tiledb_vfs_fh_tpp(long jarg1);

  public final static native void delete_tiledb_vfs_fh_tpp(long jarg1);

  public final static native void tiledb_vfs_fh_tpp_assign(long jarg1, long jarg2);

  public final static native long tiledb_vfs_fh_tpp_value(long jarg1);

  public final static native long new_tiledb_object_tp();

  public final static native long copy_tiledb_object_tp(long jarg1);

  public final static native void delete_tiledb_object_tp(long jarg1);

  public final static native void tiledb_object_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_object_tp_value(long jarg1);

  public final static native long new_tiledb_query_type_tp();

  public final static native long copy_tiledb_query_type_tp(long jarg1);

  public final static native void delete_tiledb_query_type_tp(long jarg1);

  public final static native void tiledb_query_type_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_query_type_tp_value(long jarg1);

  public final static native long new_tiledb_query_status_tp();

  public final static native long copy_tiledb_query_status_tp(long jarg1);

  public final static native void delete_tiledb_query_status_tp(long jarg1);

  public final static native void tiledb_query_status_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_query_status_tp_value(long jarg1);

  public final static native long new_tiledb_filesystem_tp();

  public final static native long copy_tiledb_filesystem_tp(long jarg1);

  public final static native void delete_tiledb_filesystem_tp(long jarg1);

  public final static native void tiledb_filesystem_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_filesystem_tp_value(long jarg1);

  public final static native long new_tiledb_datatype_tp();

  public final static native long copy_tiledb_datatype_tp(long jarg1);

  public final static native void delete_tiledb_datatype_tp(long jarg1);

  public final static native void tiledb_datatype_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_datatype_tp_value(long jarg1);

  public final static native long new_tiledb_array_type_tp();

  public final static native long copy_tiledb_array_type_tp(long jarg1);

  public final static native void delete_tiledb_array_type_tp(long jarg1);

  public final static native void tiledb_array_type_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_array_type_tp_value(long jarg1);

  public final static native long new_tiledb_layout_tp();

  public final static native long copy_tiledb_layout_tp(long jarg1);

  public final static native void delete_tiledb_layout_tp(long jarg1);

  public final static native void tiledb_layout_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_layout_tp_value(long jarg1);

  public final static native long new_tiledb_compressor_tp();

  public final static native long copy_tiledb_compressor_tp(long jarg1);

  public final static native void delete_tiledb_compressor_tp(long jarg1);

  public final static native void tiledb_compressor_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_compressor_tp_value(long jarg1);

  public final static native long new_tiledb_walk_order_tp();

  public final static native long copy_tiledb_walk_order_tp(long jarg1);

  public final static native void delete_tiledb_walk_order_tp(long jarg1);

  public final static native void tiledb_walk_order_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_walk_order_tp_value(long jarg1);

  public final static native long new_tiledb_vfs_mode_tp();

  public final static native long copy_tiledb_vfs_mode_tp(long jarg1);

  public final static native void delete_tiledb_vfs_mode_tp(long jarg1);

  public final static native void tiledb_vfs_mode_tp_assign(long jarg1, long jarg2);

  public final static native long tiledb_vfs_mode_tp_value(long jarg1);
}
