/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public enum tiledb_field_origin_t {
  TILEDB_ATTRIBUTE_FIELD(0),
  TILEDB_DIMENSION_FIELD,
  TILEDB_AGGREGATE_FIELD;

  public final int swigValue() {
    return swigValue;
  }

  public static tiledb_field_origin_t swigToEnum(int swigValue) {
    tiledb_field_origin_t[] swigValues = tiledb_field_origin_t.class.getEnumConstants();
    if (swigValue < swigValues.length
        && swigValue >= 0
        && swigValues[swigValue].swigValue == swigValue) return swigValues[swigValue];
    for (tiledb_field_origin_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue) return swigEnum;
    throw new IllegalArgumentException(
        "No enum " + tiledb_field_origin_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private tiledb_field_origin_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private tiledb_field_origin_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue + 1;
  }

  @SuppressWarnings("unused")
  private tiledb_field_origin_t(tiledb_field_origin_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue + 1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}
