/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public enum tiledb_data_order_t {
  TILEDB_UNORDERED_DATA(0),
  TILEDB_INCREASING_DATA(1),
  TILEDB_DECREASING_DATA(2);

  public final int swigValue() {
    return swigValue;
  }

  public static tiledb_data_order_t swigToEnum(int swigValue) {
    tiledb_data_order_t[] swigValues = tiledb_data_order_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (tiledb_data_order_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + tiledb_data_order_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private tiledb_data_order_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private tiledb_data_order_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private tiledb_data_order_t(tiledb_data_order_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

