/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.tiledb.libtiledb;

public enum tiledb_filter_webp_format_t {
  TILEDB_WEBP_NONE(0),
  TILEDB_WEBP_RGB(1),
  TILEDB_WEBP_BGR(2),
  TILEDB_WEBP_RGBA(3),
  TILEDB_WEBP_BGRA(4);

  public final int swigValue() {
    return swigValue;
  }

  public static tiledb_filter_webp_format_t swigToEnum(int swigValue) {
    tiledb_filter_webp_format_t[] swigValues = tiledb_filter_webp_format_t.class.getEnumConstants();
    if (swigValue < swigValues.length
        && swigValue >= 0
        && swigValues[swigValue].swigValue == swigValue) return swigValues[swigValue];
    for (tiledb_filter_webp_format_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue) return swigEnum;
    throw new IllegalArgumentException(
        "No enum " + tiledb_filter_webp_format_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private tiledb_filter_webp_format_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private tiledb_filter_webp_format_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue + 1;
  }

  @SuppressWarnings("unused")
  private tiledb_filter_webp_format_t(tiledb_filter_webp_format_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue + 1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}
